{
  "hash": "c04cb76ba4bbb1e10b858a19caef240a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Supplementary Material — Analysis Pipeline\"\nsubtitle: \"Parallel elevation filtering of Ericaceae root-associated fungal communities in Andean páramo ecosystems\"\ndate: \"2026-04-22\"\nformat:\n  pdf:\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contents\"\n    pdf-engine: xelatex\n    geometry: \"margin=2.5cm\"\n    fontsize: 11pt\n    keep-tex: false\n    include-in-header:\n      text: |\n        \\usepackage{booktabs}\n        \\usepackage{longtable}\n        \\usepackage{float}\n        \\floatplacement{figure}{H}\n        \\usepackage{fvextra}\n        \\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\\\\{\\}}\n        \\usepackage{caption}\n        \\captionsetup[table]{labelformat=empty}\n        \\captionsetup[longtable]{labelformat=empty}\nexecute:\n  echo: false\n  warning: false\n  message: false\neditor: visual\n---\n\n```{=latex}\n\\newpage\n```\n\n## Overview and reproducibility\n\nThis document compiles methodological details, supplementary analyses, and reproducibility outputs supporting the main manuscript. Computationally intensive steps (e.g. phylogenetic tree inference, GLLVM fitting, iNEXT3D diversity estimation) were executed on a remote Ubuntu-based computing environment. Their outputs (figures, tables, and selected model objects) are integrated here as static results.\n\nThis PDF is a static, code-free version of the supplementary material intended for journal submission. All underlying code is available in the reproducible HTML companion ([`Appendix_HTML.html`](https://ssangulo.github.io/Paramo_SkyIslands_RootFungi/appendix.html)), which includes collapsible code blocks for all analyses. The Quarto source file (`Analysis_pipeline.qmd`), data, figures, and tables are archived in the project repository.\n\n**Data availability.**\n\nRepository: [Paramo_SkyIslands_RootFungi](https://github.com/Ssangulo/Paramo_SkyIslands_RootFungi) \\\nSequence data: ENA accession number PRJEB107725\\\nMetadata: `Data_S1_metadata.csv, Data_S3_soil.csv`\n\nHTML reproducible appendix: [`Appendix_HTML.html`](https://ssangulo.github.io/Paramo_SkyIslands_RootFungi/appendix.html)\n\n\n::: {.cell}\n\n:::\n\n\n------------------------------------------------------------------------\n\n## Section 0: Setup {.unnumbered}\n\nOutput directory paths and shared aesthetic constants used throughout this document. All packages are loaded locally within each code section.\n\n*Code: see \"Section 0: Setup\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n\n------------------------------------------------------------------------\n\n## Section 1: Data and object loading {.unnumbered}\n\nAll pre-computed R objects are loaded here. Computationally intensive analyses (GLLVM, iNEXT3D, NTI/NRI, phylogeny inference) were executed on a remote server; their outputs are stored in `objects/` and loaded as needed.\n\n*Code: see \"Section 1: Data and object loading\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n```{=latex}\n\\newpage\n```\n\n## Section 2: Bioinformatics summary and study design\n\n### 2.1 Study sites and sampling\n\nThis study was conducted across four humid páramo regions in the Colombian Andes, spanning the Central and Eastern Cordilleras. Sampling locations covered elevations from 2,715 to 3,828 m a.s.l., representing the ecological transition from Andean forest to páramo (see main text, Fig. 1). The full sample metadata table is provided in Data_S1_metadata.csv.\n\nRoot sampling followed standardized sterile procedures. Fine roots of Gaultheria myrsinoides were excavated using a spade, and 3–5 cm root tips were clipped using a sterilized pruner. Tools were disinfected with 75% ethanol between samples, and gloves were changed between individual plants to minimize contamination. Root fragments were placed into sealed polybags stored in ice-cooled containers in the field. Samples were processed at Universidad ICESI, where roots were rinsed in sterile water to remove debris, dried briefly under a laminar flow hood, and stored at –20°C prior to shipment to Norway, and long-term storage at –80°C. Soil samples (top 15 cm) were collected at each sampling location, and five aliquots of rinse water were retained as laboratory and transport controls.\n\n**Table S1**: GPS coordinates, elevation, and vegetation type classification of the 12 sampling locations across four páramo regions. These sites span the forest–subpáramo–páramo gradient and were used for root and soil sampling. In each location, 10 root samples were collected from 5 individuals (2 root samples per individual) and 1 soil sample.\n\n|             |                      |                  |                  |                   |               |\n|------------|------------|------------|------------|------------|------------|\n| **Site ID** | **Site**             | **Altitude (m)** | **Latitude (N)** | **Longitude (W)** | **Ecosystem** |\n| NV_1        | Páramo La Nevera     | 3828             | 03º30'58.1\"      | 076º03'05.4\"      | Páramo        |\n| NV_2        | Páramo La Nevera     | 3550             | 03º31'37.7\"      | 076º03'38.7\"      | Subpáramo     |\n| NV_3        | Páramo La Nevera     | 3333             | 03º32'07.0\"      | 076º04'18.3\"      | Andean forest |\n| NV_4        | Páramo La Nevera     | 3078             | 03º32'48.9\"      | 076º04'31.3\"      | Andean forest |\n| DOM_1       | Páramo Las Domínguez | 3815             | 03º43'51.8\"      | 076º06'38.1\"      | Páramo        |\n| DOM_2       | Páramo Las Domínguez | 3534             | 03º44'07.2\"      | 076º05'53.2\"      | Subpáramo     |\n| DOM_3       | Páramo Las Domínguez | 3234             | 03º44'17.1\"      | 076º05'32.9\"      | Andean forest |\n| BEL_1       | Páramo Belmira       | 3254             | 06º38'43.8\"      | 075º40'13.3\"      | Subpáramo     |\n| BEL_2       | Páramo Belmira       | 2950             | 06º38'22.7\"      | 075º39'57.3\"      | Andean forest |\n| BEL_3       | Páramo Belmira       | 2715             | 06°36'55.3\"      | 075°39'51.1\"      | Andean forest |\n| MA_1        | Páramo Matarredonda  | 3678             | 04º33'31.5\"      | 074º01'43.8\"      | Páramo        |\n| MA_2        | Páramo Matarredonda  | 3381             | 04º33'10.3\"      | 073º59'35.3\"      | Subpáramo     |\n\n### 2.2 Read filtering, OTU table, and taxonomic assignment\n\nThis section provides supplementary details on sequencing read processing and quality filtering. The full bioinformatic pipeline (including DADA2 processing and replicate filtering) is available in the project repository. Here we report summary tables of read retention and replicate-filtering thresholds used for downstream analyses.\n\n**Table S2**: Median read numbers per PCR replicate for environmental samples (root and soil samples) and controls (blank extractions, positive, PCR blank, and tag-jump controls). The read counts are grouped at each stage of the DADA2 pipeline. Blank extraction controls (not containing any biological sample) were performed alongside real sample DNA extractions per each extraction batch. PCR blank controls contained all PCR reagents but no DNA template. Tag-jump controls are PCR reactions containing no primers and no DNA template, used to detect tag-jumping (index hopping).\n\n|                               |               |              |                         |                     |                           |\n|------------|------------|------------|------------|------------|------------|\n|                               | **Raw reads** | **Filtered** | **Merged - Non pooled** | **Merged - Pooled** | **Merged - Pseudopooled** |\n| **Root samples**              | 77,047        | 71,783       | 71,084                  | 70,343              | 71,242                    |\n| **Soil samples**              | 72,158        | 66,555       | 65,311                  | 65,498              | 65,385                    |\n| **Blank Extraction Controls** | 2,844         | 2,652        | 2,618                   | 2,566               | 2,625                     |\n| **Positive Controls**         | 95,238        | 88,174       | 88,062                  | 87,996              | 87,972                    |\n| **PCR Blank Controls**        | 291           | 261          | 250                     | 257                 | 256                       |\n| **Tag-jump Controls**         | 41            | 36           | 27                      | 30                  | 32                        |\n\n------------------------------------------------------------------------\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S3. Number of OTUs and samples after applying different replicate control filtering thresholds. The table shows results for both soil and root samples combined and only root samples.\n\n|Filtering level    | OTUs (all)| Samples (all)| OTUs (root)| Samples (root)|\n|:------------------|----------:|-------------:|-----------:|--------------:|\n|No filtering       |      18451|           132|       13225|            120|\n|OTU present in 2/4 |       7174|           132|        4386|            120|\n|OTU present in 3/4 |       4870|           131|        2966|            120|\n|OTU present in 4/4 |       2875|           113|        1904|            103|\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n**Table S4**: Summary of the percentage of reads and OTUs with confident taxonomic assignment at each taxonomic rank, represented by habitat. Percentages were calculated from the filtered root-only dataset (soil reads removed).\n\n|          |             |                       |                      |\n|----------|-------------|-----------------------|----------------------|\n| **Rank** | **Habitat** | **%\\_reads_assigned** | **%\\_otus_assigned** |\n| Phylum   | Forest      | 88,1                  | 88,1                 |\n| Phylum   | Subpáramo   | 91,6                  | 88,6                 |\n| Phylum   | Páramo      | 92,9                  | 89,3                 |\n| Class    | Forest      | 78,3                  | 72,5                 |\n| Class    | Subpáramo   | 84,2                  | 72,3                 |\n| Class    | Páramo      | 84,3                  | 76,0                 |\n| Order    | Forest      | 68,3                  | 59,2                 |\n| Order    | Subpáramo   | 74,2                  | 57,1                 |\n| Order    | Páramo      | 78,2                  | 60,9                 |\n| Genus    | Forest      | 32,8                  | 34,2                 |\n| Genus    | Subpáramo   | 32,1                  | 32,2                 |\n| Genus    | Páramo      | 31,4                  | 32,7                 |\n\n\n```{=latex}\n\\newpage\n```\n\n## Section 3: Taxonomic overview\n\n![](figures/Fig_S1_Venn.png){width=\"90%\"}\n\n**Figure S1**: Venn diagram of taxonomic assignments across sampling sites, in the root only dataset, but previous to soil sequences removal. Venn diagrams illustrate the overlap of OTU taxonomic assignments across four study sites: La Nevera (NV), Las Domínguez (DOM), Belmira (BEL), and Matarredonda (MA). Only OTUs with confirmed assignments at each taxonomic level are included.\n\n------------------------------------------------------------------------\n\n![](figures/Fig_S2.png){width=\"100%\"}\n\n**Figure S2**: Taxonomic composition in root samples along the elevational gradient. Relative read abundances are shown at three taxonomic ranks: A) Phylum, B) Genus and C) Order. Each bar represents an individual root sample, grouped by habitat: Forest (2700–3300 m), Subpáramo (3300–3500 m), and Páramo (3800 m). Study sites are indicated on the y-axis. *Code: see \"MicroViz code for taxonomic barplots\" in Appendix_HTML.html.*\n\n------------------------------------------------------------------------\n\n![](figures/Fig_S3.png){width=\"100%\"}\n\n**Figure S3**: Taxonomic composition in soil samples, collected at each of the sampling locations. Relative read abundances are shown at three taxonomic ranks: A) Phylum, B) Genus, and C) Order. Each bar represents an individual soil sample, grouped by habitat: Forest (2700–3300 m), Subpáramo (3300–3500 m), and Páramo (3800 m). Study sites are indicated on the y-axis. *Code: see \"MicroViz code for taxonomic barplots\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n```{=latex}\n\\newpage\n```\n\n## Section 4: Community composition\n\nThis section provides detailed statistical analyses supporting the patterns of root-associated fungal community composition described in the main text. Several of these analyses form the basis of results reported in the main manuscript; here we document the full model specifications, test statistics, and complementary ordinations to ensure transparency and reproducibility.\n\nWe include distance-based redundancy analysis (dbRDA) based on robust Aitchison distances to assess habitat-associated compositional structure while conditioning on site. We further present PERMANOVA results from a balanced subset of samples (NV–DOM) used to test habitat and site effects under a controlled sampling design. In addition, we report a centroid-based turnover model quantifying the magnitude of community change across habitats using the full dataset.\n\n### 4.1 dbRDA ordination (Tables S5–S6)\n\nDistance-based redundancy analysis (dbRDA) was conducted on robust Aitchison distances to test for habitat-associated compositional structure while conditioning on site. This analysis is reported in the main manuscript as Figure 2A (habitat separation conditioned on site; permutation test $F=1.41$, $p=0.001$).\n\n------------------------------------------------------------------------\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S5. dbRDA permutation tests (by term; 999 permutations).\n\n|Component | Df| Variance|     F|    Pr|\n|:---------|--:|--------:|-----:|-----:|\n|habitat   |  2|   22.718| 1.408| 0.001|\n|Residual  | 54|  435.501|    NA|    NA|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S6. dbRDA permutation tests (by constrained axis; 999 permutations).\n\n|Axis     | Df| Variance|     F|    Pr|\n|:--------|--:|--------:|-----:|-----:|\n|CAP1     |  1|   14.579| 1.808| 0.001|\n|CAP2     |  1|    8.139| 1.009| 0.470|\n|Residual | 54|  435.501|    NA|    NA|\n\n\n:::\n:::\n\n\n*Code: see \"Code used to generate Tables S5–S6 and dbRDA support plot\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n\n### 4.2 PERMANOVA and beta-dispersion (Tables S7–S9)\n\nBeta-dispersion tests indicated higher within-habitat variability in forests compared with subpáramo and páramo communities (p \\< 0.001), whereas dispersion did not differ among sites (p = 0.526). Because the PERMANOVA was conducted on a balanced subset of samples, the significant effects of habitat, site, and their interaction are interpreted as reflecting genuine compositional differences rather than artifacts of unequal dispersion. *Code: see \"Code used to generate Tables S7–S9\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S7. PERMANOVA (adonis2) results by term.\n\n|Source       | df|  SumOfSqs|    R2| Pseudo.F| Pr..F.|\n|:------------|--:|---------:|-----:|--------:|------:|\n|site         |  1|   742.078| 0.056|    1.786|  0.001|\n|habitat      |  2|  1351.164| 0.102|    1.626|  0.001|\n|site:habitat |  2|  1241.269| 0.093|    1.493|  0.001|\n|Residual     | 24|  9974.546| 0.749|       NA|     NA|\n|Total        | 29| 13309.057| 1.000|       NA|     NA|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S8. Habitat beta-dispersion (distance to centroid). Permutation test p = 0.001.\n\n|habitat   | avg_distance_to_centroid|\n|:---------|------------------------:|\n|forest    |                   23.631|\n|paramo    |                   17.147|\n|subparamo |                   17.794|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S9. Site beta-dispersion permutation test.\n\n|test            | permutations|     F| p_value|\n|:---------------|------------:|-----:|-------:|\n|betadisper_site |          999| 0.314|   0.571|\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n### 4.3 Centroid-based turnover model (Table S10)\n\nTo quantify the magnitude of community turnover across habitats while accounting for spatial structure, we calculated the Aitchison distance of each sample to its site-specific centroid and modelled turnover as a function of habitat, site, and their interaction. Habitat had a strong effect on turnover magnitude, whereas the habitat × site interaction was not significant, indicating consistent habitat-associated turnover across geographically isolated páramo regions (Table S10).\n\nPanel B in the main manuscript Figure 2 summarizes this model (habitat $F_{2,50}=14.7$, $p<0.001$; habitat × site $F_{4,50}=1.28$, $p=0.29$), with Matarredonda (MA) shown as a dashed trend due to a compressed gradient.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S10. Linear model results for centroid-based turnover.\n\n|Effect       | df| Sum.of.Squares| Mean.Square| F.value| p.value|\n|:------------|--:|--------------:|-----------:|-------:|-------:|\n|habitat      |  2|        376.745|     188.373|  14.719|   0.000|\n|site         |  3|        138.096|      46.032|   3.597|   0.020|\n|habitat:site |  4|         65.496|      16.374|   1.279|   0.291|\n|Residuals    | 50|        639.914|      12.798|      NA|      NA|\n\n\n:::\n:::\n\n\n*Code: see \"Code used to generate Table S10\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n\n### 4.4 Figure 2\n\n![](figures/Figure_2_dbRDA_centroid.png){width=\"100%\"}\n\n**Figure 2**: Community composition and turnover across habitats. Panel A: dbRDA ordination of RAF communities conditioned on site (color = site, shape = habitat; permutation $F=1.41$, $p=0.001$). Panel B: centroid-based turnover model (distance to site-specific centroid across habitats), with MA shown as dashed due to incomplete gradient (habitat $F_{2,50}=14.7$, $p<0.001$; habitat × site $F_{4,50}=1.28$, $p=0.29$). *Code: see \"Code used to generate Figure 2\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n```{=latex}\n\\newpage\n```\n\n## Section 5: Diversity trajectories\n\nDiversity trajectories were assessed using three complementary approaches: per-sample Hill diversity models to test parallelism across sites, iNEXT3D rarefaction/extrapolation curves for habitat-level estimates, and beta-diversity partitioning. All analyses require a rooted phylogenetic tree, inferred from a GTR+Γ model.\n\n*Code for phylogenetic tree inference: see \"Phylogenetic tree inference (GTR+Γ; executed on server)\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n\n### 5.1 Per-sample Hill diversity: parallelism models (Tables S18–S19)\n\nTo evaluate whether diversity trajectories are parallel across geographically isolated sites, we model diversity as a function of habitat (ordered along elevation), site, and their interaction. The key term is habitat × site: a weak/non-significant interaction with a strong habitat main effect supports broadly parallel trajectories with site-specific baselines.\n\nFor this section, diversity is computed independently for each sample using Hill numbers: taxonomic diversity (TD) and phylogenetic diversity (PD) at q = 1 (effective Shannon) as the primary metric. We use a two-model strategy: (i) a primary habitat-factor model for ecological interpretation, and (ii) a secondary numeric-trend model (ordered habitat steps) to summarize site-specific slopes. Model family is screened first (Gaussian, log-Gaussian, Gamma-log) before final inference.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S18. ANOVA table for the log-linear model of per-sample taxonomic diversity (TD; Hill q=1) as a function of habitat, site, and their interaction. Habitat × site interaction F(4,50)=1.52, p=0.21 supports parallel diversity trajectories across sites.\n\n|Term         | Df| Sum.Sq| Mean.Sq| F.value| Pr..F.|\n|:------------|--:|------:|-------:|-------:|------:|\n|habitat      |  2|  2.748|   1.374|   4.395|  0.017|\n|site         |  3|  0.633|   0.211|   0.675|  0.571|\n|habitat:site |  4|  1.899|   0.475|   1.518|  0.211|\n|Residuals    | 50| 15.633|   0.313|      NA|     NA|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S19. ANOVA table for the log-linear model of per-sample phylogenetic diversity (PD; Hill q=1, meanPD) as a function of habitat, site, and their interaction. Habitat × site interaction F(4,50)=1.22, p=0.31 supports parallel diversity trajectories across sites.\n\n|Term         | Df| Sum.Sq| Mean.Sq| F.value| Pr..F.|\n|:------------|--:|------:|-------:|-------:|------:|\n|habitat      |  2|  1.135|   0.568|   3.027|  0.057|\n|site         |  3|  0.794|   0.265|   1.411|  0.251|\n|habitat:site |  4|  0.918|   0.230|   1.224|  0.313|\n|Residuals    | 50|  9.375|   0.188|      NA|     NA|\n\n\n:::\n:::\n\n\n*Code: see \"Per-sample Hill TD/PD: family checks + primary factor model + secondary slope model\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n\n### 5.2 iNEXT3D rarefaction curves and asymptotic diversity summaries (Tables S16–S17)\n\nWe quantified habitat-associated patterns in taxonomic diversity (TD) and phylogenetic diversity (PD) using iNEXT3D and Hill numbers (q = 0, 1, 2). Diversity estimates were computed from incidence (presence/absence) matrices at the habitat level and evaluated under rarefaction/extrapolation with bootstrap confidence intervals (nboot = 500). Phylogenetic diversity was estimated as meanPD using a pruned phylogeny matched to the observed taxa. The combined curve visualization is presented in main-text Figure 3A; asymptotic summaries are provided in Tables S16–S17, and the per-sample parallelism ANOVA results in Tables S18–S19.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S16. Taxonomic diversity (TD) summary from iNEXT3D across habitats (q = 0, 1, 2; nboot = 500). Observed and asymptotic estimates are reported with standard errors, 95% confidence intervals, and sample coverage at observed effort and at double effort.\n\n|Assemblage |qTD               |   TD_obs|   TD_asy|    s.e.|  qTD.LCL|  qTD.UCL|\n|:----------|:-----------------|--------:|--------:|-------:|--------:|--------:|\n|Forest     |Species richness  | 2521.000| 4581.983| 125.848| 4335.326| 4828.640|\n|Forest     |Shannon diversity | 1810.823| 2927.463|  51.242| 2827.030| 3027.896|\n|Forest     |Simpson diversity | 1158.528| 1467.726|  34.168| 1400.758| 1534.695|\n|Páramo     |Species richness  |  901.000| 1945.702|  95.214| 1759.086| 2132.317|\n|Páramo     |Shannon diversity |  693.768| 1316.325|  43.456| 1231.153| 1401.497|\n|Páramo     |Simpson diversity |  474.571|  661.005|  30.584|  601.061|  720.948|\n|Subpáramo  |Species richness  | 1533.000| 3059.820| 108.142| 2847.866| 3271.775|\n|Subpáramo  |Shannon diversity | 1225.295| 2341.860|  58.351| 2227.494| 2456.226|\n|Subpáramo  |Simpson diversity |  846.718| 1247.075|  49.323| 1150.403| 1343.747|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S17. Phylogenetic diversity (PD; meanPD) summary from iNEXT3D across habitats (q = 0, 1, 2; nboot = 500), including coverage and effective lineage estimates under rarefaction/extrapolation.\n\n|Habitat   |qPD      |  PD_obs|  PD_asy|  s.e.| qPD.LCL| qPD.UCL| Reftime|Type   |\n|:---------|:--------|-------:|-------:|-----:|-------:|-------:|-------:|:------|\n|Forest    |q = 0 PD | 185.553| 283.343| 7.643| 268.362| 298.324|   0.873|meanPD |\n|Forest    |q = 1 PD |  96.045| 115.843| 1.427| 113.045| 118.641|   0.873|meanPD |\n|Forest    |q = 2 PD |  53.644|  56.697| 0.585|  55.551|  57.842|   0.873|meanPD |\n|Páramo    |q = 0 PD |  81.971| 134.076| 6.501| 121.334| 146.818|   0.873|meanPD |\n|Páramo    |q = 1 PD |  46.984|  60.900| 1.321|  58.310|  63.489|   0.873|meanPD |\n|Páramo    |q = 2 PD |  27.101|  29.356| 0.529|  28.320|  30.392|   0.873|meanPD |\n|Subpáramo |q = 0 PD | 132.936| 213.016| 7.909| 197.514| 228.518|   0.873|meanPD |\n|Subpáramo |q = 1 PD |  75.157|  98.360| 1.843|  94.748| 101.973|   0.873|meanPD |\n|Subpáramo |q = 2 PD |  39.842|  43.233| 0.715|  41.831|  44.635|   0.873|meanPD |\n\n\n:::\n:::\n\n\n*Code: see \"iNEXT3D diversity analyses (executed on remote server)\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n\n------------------------------------------------------------------------\n\n### 5.3 Abundance-based beta-diversity partitioning (Table S11)\n\nBray–Curtis dissimilarities were partitioned into balanced variation and abundance gradients across taxonomic levels using the `betapart` package. Metrics were calculated from rarefied abundance data.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S11. Bray–Curtis beta-diversity partitioning across taxonomic levels and sites.\n\n|Site |Taxonomic_Level | beta.BRAY.BAL| beta.BRAY.GRA| beta.BRAY|\n|:----|:---------------|-------------:|-------------:|---------:|\n|DOM  |OTU             |        0.9748|        0.0244|    0.9993|\n|DOM  |Genus           |        0.9164|        0.0780|    0.9944|\n|DOM  |Order           |        0.7708|        0.2166|    0.9874|\n|DOM  |Class           |        0.4256|        0.5418|    0.9674|\n|DOM  |Phylum          |        0.2759|        0.6859|    0.9619|\n|NV   |OTU             |        0.9870|        0.0124|    0.9995|\n|NV   |Genus           |        0.9553|        0.0415|    0.9969|\n|NV   |Order           |        0.7846|        0.2059|    0.9905|\n|NV   |Class           |        0.4516|        0.5238|    0.9754|\n|NV   |Phylum          |        0.1470|        0.8046|    0.9516|\n|BEL  |OTU             |        0.9870|        0.0125|    0.9994|\n|BEL  |Genus           |        0.9371|        0.0573|    0.9945|\n|BEL  |Order           |        0.7916|        0.1995|    0.9911|\n|BEL  |Class           |        0.4611|        0.5121|    0.9733|\n|BEL  |Phylum          |        0.0258|        0.9434|    0.9692|\n|MA   |OTU             |        0.9431|        0.0557|    0.9989|\n|MA   |Genus           |        0.9305|        0.0627|    0.9932|\n|MA   |Order           |        0.7966|        0.1911|    0.9877|\n|MA   |Class           |        0.5906|        0.3750|    0.9656|\n|MA   |Phylum          |        0.0000|        0.9504|    0.9505|\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### 5.4 Figure 3: Diversity trajectories\n\n![](figures/Figure_3_iNEXT_rarefaction_trajectories.png){width=\"100%\"}\n\n**Figure 3**: Diversity decline across the elevational gradient. Panel A shows iNEXT3D coverage-based rarefaction/extrapolation curves for TD and PD at $q=0,1,2$ by habitat. Panel B shows per-sample Hill diversity trajectories ($q=1$) for TD and PD, with model-estimated means ± 95% CI for BEL, DOM, and NV (MA excluded). Habitat × site interactions were non-significant for both metrics (TD $F_{4,50}=1.52$, $p=0.21$; PD $F_{4,50}=1.22$, $p=0.31$), supporting parallel diversity erosion across regions. *Code: see \"Code used to generate Figure 3\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n```{=latex}\n\\newpage\n```\n\n## Section 6: Lineage-specific responses\n\n### 6.1 Beta regression models (Tables S12–S14)\n\nTo quantify elevational trends in the relative abundance of dominant fungal lineages, we fitted beta-regression models to order-level relative read abundances. Models were fitted separately for each order using a logit link, with elevation as a continuous predictor and site included as a fixed effect. Relative abundances were calculated as proportions of total reads per sample and transformed using a Smithson–Verkuilen adjustment.\n\nWe focus on Helotiales and Sebacinales, the two most abundant orders, which also showed the only significant elevation responses. For both orders, fitted relationships and raw data are shown in Figure 4 (Panels A–B), while full model summaries are provided in Tables S12 and S13. Elevation effects for the eight most abundant orders are summarized in Table S14.\n\nModel diagnostics were examined to assess fit and identify potential violations of distributional assumptions. Diagnostic plots include Pearson residuals versus fitted values and elevation, quantile residual Q–Q plots, and leverage values (Figures S5–S6).\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S12. Beta regression summary for Helotiales (mean model coefficients and precision (phi)).\n\n|Model      |Term        | Estimate|     SE|       z|      p|\n|:----------|:-----------|--------:|------:|-------:|------:|\n|helotiales |(Intercept) |  -3.2040| 1.2559| -2.5512| 0.0107|\n|helotiales |elevation   |   0.0010| 0.0004|  2.3959| 0.0166|\n|helotiales |siteDOM     |  -0.7291| 0.3651| -1.9969| 0.0458|\n|helotiales |siteMA      |   0.0050| 0.3871|  0.0130| 0.9896|\n|helotiales |siteNV      |  -0.8864| 0.3346| -2.6494| 0.0081|\n|helotiales |(phi) (phi) |   6.2698| 1.0711|  5.8534| 0.0000|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S13. Beta regression summary for Sebacinales (mean model coefficients and precision (phi)).\n\n|Model       |Term        | Estimate|     SE|       z|      p|\n|:-----------|:-----------|--------:|------:|-------:|------:|\n|sebacinales |(Intercept) |   0.4169| 1.3941|  0.2990| 0.7649|\n|sebacinales |elevation   |  -0.0010| 0.0005| -2.1320| 0.0330|\n|sebacinales |siteDOM     |   0.7196| 0.4162|  1.7289| 0.0838|\n|sebacinales |siteMA      |   0.3029| 0.4603|  0.6580| 0.5105|\n|sebacinales |siteNV      |   0.9779| 0.3714|  2.6333| 0.0085|\n|sebacinales |(phi) (phi) |  10.1810| 2.0241|  5.0298| 0.0000|\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S14. Elevation effects from beta regression models for the dominant orders (mean submodel), with pseudo-R².\n\n|order           |term      | estimate|    se|       z| p_value| pseudo_R2|\n|:---------------|:---------|--------:|-----:|-------:|-------:|---------:|\n|helotiales      |elevation |    1e-03| 4e-04|  2.3959|  0.0166|    0.2133|\n|sebacinales     |elevation |   -1e-03| 5e-04| -2.1320|  0.0330|    0.2261|\n|chaetothyriales |elevation |    1e-04| 4e-04|  0.2327|  0.8160|    0.0239|\n|sclerococcales  |elevation |    7e-04| 5e-04|  1.3758|  0.1689|    0.1330|\n|agaricales      |elevation |   -7e-04| 4e-04| -1.7597|  0.0785|    0.0929|\n|pleosporales    |elevation |   -4e-04| 4e-04| -1.0668|  0.2861|    0.1528|\n|hypocreales     |elevation |   -2e-04| 3e-04| -0.7300|  0.4654|    0.2397|\n|leotiales       |elevation |   -2e-04| 3e-04| -0.6812|  0.4957|    0.2964|\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n![](figures/Fig_S5_betareg_diagnostics_helotiales.png){width=\"95%\"}\n\n**Figure S5**: Diagnostic plots for the beta-regression model of Helotiales. *Code: see \"Beta-regression models (executed on remote server)\" in Appendix_HTML.html.*\n\n------------------------------------------------------------------------\n\n![](figures/Fig_S6_betareg_diagnostics_sebacinales.png){width=\"95%\"}\n\n**Figure S6**: Diagnostic plots for the beta-regression model of Sebacinales. *Code: see \"Beta-regression models (executed on remote server)\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n\n### 6.2 Figure 4: Elevational trends and OTU habitat responses\n\nThree-panel composite figure combining order-level elevational trends (beta-regression for the two most abundant and responsive orders) with OTU-level habitat associations from the GLLVM model. Panel A and B show fitted beta-regression relationships for *Helotiales* and *Sebacinales* across sampling sites with raw data overlaid. Panel C presents the genus-level GLLVM heatmap showing weighted habitat contrast effects (páramo and subpáramo relative to forest) for the most responsive taxa.\n\n![](figures/Figure_4_betareg_GLLVM_combined.png){width=\"100%\"}\n\n**Figure 4**: Elevational trends and OTU-level habitat responses. Panel A: Helotiales relative abundance versus elevation (approximately +10.1% per 100 m, $p=0.016$). Panel B: Sebacinales relative abundance versus elevation (approximately -10.0% per 100 m, $p=0.033$). Panel C: GLLVM heatmap of genus-level coefficients for páramo vs forest and subpáramo vs forest contrasts. *Code: see \"Code used to generate Figure 4\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n\n### 6.3 GLLVM: OTU-level habitat responses\n\nWe modelled OTU counts using a generalized linear latent variable model (GLLVM; negative binomial distribution, log link), with habitat (forest, subpáramo, páramo) as a fixed effect, log library size as an offset, and random intercepts for site and individual plants (Unique_ID). One latent variable was included to account for residual correlation among taxa. The final model (log-likelihood = −37,616; AIC = 80,295) provided the best balance between fit and parsimony. It substantially outperformed earlier versions with nested random effects (AIC = 186,832), and attempts to increase the number of latent variables to two worsened performance (ΔAIC ≈ 12,700) and produced a singular information matrix, indicating over-parameterization. Simplifying the random-effects structure and filtering rare taxa also improved convergence and reduced overdispersion while retaining ecological signal.\n\nModel fit was evaluated using Dunn–Smyth residual diagnostics (Fig. S8). Habitat coefficients (β) were extracted for each OTU from the fixed-effects matrix. To obtain genus-level responses, OTUs were restricted to those assigned to a genus (excluding incertae sedis) and weighted by their total read abundance across samples. For each genus, we computed the abundance-weighted mean β for páramo and subpáramo relative to forest. Uncertainty was summarized using a weighted bootstrap (R = 500) resampling OTUs within genera with probabilities proportional to total abundance; 2.5–97.5% quantiles were used as 95% confidence intervals. These summaries were used to generate the heatmap and barplot shown in Figure 4. The full OTU-level coefficient table is provided in Data_S2_GLLVM_table.csv.\n\n![](figures/Fig_S8_GLLVM_diagnostics.png){width=\"95%\"}\n\n**Figure S8**: Diagnostic plots for the negative-binomial GLLVM (Dunn–Smyth residuals). *Code: see \"GLLVM model fitting + coefficient summaries (executed on server)\" in Appendix_HTML.html.*\n\nFor transparency, we provide a short preview of the genus-level GLLVM summaries below. The complete OTU- and genus-level coefficient table is available as Data S2 (Data_S2_GLLVM_table.csv).\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{9}{11}\\selectfont\n\n\\begin{longtable}[t]{llrrrrr}\n\\caption{\\label{tab:gllvm-preview}Data S2 (preview). Selected columns from the GLLVM genus-level summary. The full table with all metrics is provided as a CSV file.}\\\\\n\\toprule\nOrder & Genus & OTUs & β Páramo & β Subp. & Enr. Páramo (\\textbackslash{}\\%) & Enr. Subp. (\\textbackslash{}\\%)\\\\\n\\midrule\nConiochaetales & Coniochaeta & 2 & 254.379 & -25.536 & 2.048010e+115 & -1.000000e+02\\\\\nHelotiales & Acephala & 1 & 78.144 & 69.862 & 8.663205e+35 & 2.190394e+32\\\\\nHelotiales & Hyaloscypha & 3 & 26.861 & 29.053 & 3.743955e+14 & 6.764441e+13\\\\\nHelotiales & Pezicula & 5 & 26.640 & 29.280 & 1.824961e+09 & -9.894700e+01\\\\\nHelotiales & Lachnum & 3 & -1.529 & 9.013 & 1.016873e+08 & 2.107609e+04\\\\\n\\addlinespace\nSclerococcales & Sclerococcum & 4 & 24.669 & -8.648 & 2.210442e+06 & -9.989400e+01\\\\\nMortierellales & Mortierella & 5 & -7.650 & -34.063 & 1.011728e+04 & -1.000000e+02\\\\\nHelotiales & Gyoerffyella & 3 & 2.739 & 0.188 & 1.021700e+01 & -9.967900e+01\\\\\nOstropales & Cryptodiscus & 3 & -15.238 & 12.611 & -1.947200e+01 & 6.019926e+04\\\\\nHelotiales & Pezoloma & 2 & -6.125 & -4.096 & -9.964100e+01 & -9.684900e+01\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n```{=latex}\n\\newpage\n```\n\n## Section 7: Functional guilds\n\nFunctional guilds from root samples were assigned using FUNGuild based on the curated taxonomic strings exported from the phyloseq object. OTUs with a valid confidence ranking in the FUNGuild output were retained for downstream summaries. Guild labels were additionally collapsed into a primary-guild hierarchy (Ericoid mycorrhizal \\> other mycorrhizal \\> endophyte \\> pathotroph \\> saprotroph \\> other) to simplify interpretation. Figure S7 summarizes mean guild-associated read abundance per sample across habitats.\n\n![](figures/Fig_S7_FunGuild.png){width=\"95%\"}\n\n**Figure S7**: Mean relative read abundance per sample of fungal functional guilds across forest, subpáramo, and páramo habitats, based on FUNGuild annotations. Only root samples. *Code: see \"FUNGuild functional annotation (external script)\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n```{=latex}\n\\newpage\n```\n\n## Section 8: Phylogenetic community structure\n\nPhylogenetic community structure was quantified using Net Relatedness Index (NRI; based on MPD) and Nearest Taxon Index (NTI; based on MNTD), calculated under a taxa-label null model with 999 randomizations using both abundance-weighted (aw) and presence–absence (pa) versions. Habitat-level summaries are reported as median (IQR) (Table S20). Habitat and site effects on abundance-weighted metrics were evaluated with linear models (habitat + site; Table S21). Model diagnostics for the NTI_aw model are available in Fig. S9.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S20. Median (IQR) of NRI and NTI across habitats, calculated using abundance-weighted (aw) and presence–absence (pa) metrics. Positive values indicate phylogenetic clustering relative to null expectations.\n\n|Habitat   |  n|NRI_aw       |NTI_aw       |NRI_pa       |NTI_pa       |\n|:---------|--:|:------------|:------------|:------------|:------------|\n|forest    | 25|0.991 (3.02) |3.053 (1.70) |0.711 (2.19) |5.764 (2.13) |\n|paramo    | 15|1.435 (1.85) |3.277 (1.62) |0.831 (2.81) |4.930 (2.06) |\n|subparamo | 20|1.675 (1.77) |2.831 (1.40) |0.395 (1.50) |4.876 (2.49) |\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S21. ANOVA summaries for linear models of abundance-weighted NTI and NRI (habitat + site).\n\n|Response |Predictor | df|      F|      p|\n|:--------|:---------|--:|------:|------:|\n|NTI_aw   |habitat   |  2| 0.5106| 0.6030|\n|NTI_aw   |site      |  3| 1.8164| 0.1551|\n|NTI_aw   |Residuals | 54|     NA|     NA|\n|NRI_aw   |habitat   |  2| 1.2729| 0.2883|\n|NRI_aw   |site      |  3| 3.4206| 0.0235|\n|NRI_aw   |Residuals | 54|     NA|     NA|\n\n\n:::\n:::\n\n\n![](figures/Fig_S9_NTI_aw_diagnostics.png){width=\"95%\"}\n\n**Figure S9**: Diagnostic plots for the NTI_aw linear model. *Code: see \"NTI/NRI computation + summaries (executed on remote server)\" in Appendix_HTML.html.*\n\n\n::: {.cell}\n\n:::\n\n```{=latex}\n\\newpage\n```\n\n## Section 9: Soil physicochemical context\n\nTo provide environmental context for the elevational gradients sampled in this study, we quantified bulk soil physicochemical properties from one composite topsoil sample (0–15 cm) collected at each sampling location (n = 12; one per location). Because soil chemistry was measured once per location, these data are interpreted descriptively and were not used for formal statistical inference among habitats or sites.\n\nThe full soil dataset, including all measured variables, is provided as Table S15 and is archived in the repository as \"Data_S3_soil.csv\".\n\n![](figures/Fig_S10_soil.png){width=\"90%\"}\n\n**Figure S10**: Correlation heatmap of bulk soil physicochemical variables measured at each sampling location (n = 12). Colors indicate Pearson correlation among soil variables and elevation.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{longtable}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage{wrapfig}\n\\usepackage{float}\n\\usepackage{colortbl}\n\\usepackage{pdflscape}\n\\usepackage{tabu}\n\\usepackage{threeparttable}\n\\usepackage{threeparttablex}\n\\usepackage[normalem]{ulem}\n\\usepackage{makecell}\n\\usepackage{xcolor}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}