{
  "hash": "ca1753d88c11280b343a2737d2cba0a3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Supplementary Analysis Appendix\"\nsubtitle: \"Parallel elevation filtering of Ericaceae root-associated fungal communities in Andean páramo ecosystems\"\nformat:\n  html:\n    output-file: appendix.html\n    theme: cosmo\n    embed-resources: true\n    smooth-scroll: true\n    anchor-sections: true\n    code-copy: true\n    code-overflow: wrap\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contents\"\n    toc-location: left\n    number-sections: false\neditor: visual\n---\n\n\n## Overview and reproducibility\n\nThis document compiles methodological details, supplementary analyses, and reproducibility outputs supporting the main manuscript. Computationally intensive steps (e.g. phylogenetic tree inference, GLLVM fitting, iNEXT3D diversity estimation) were executed on a remote Ubuntu-based computing environment. Their outputs (figures, tables, and selected model objects) are integrated here as static results.\n\nAll figures (PNG) and result tables (CSV) are stored within the project repository using relative paths. Rendering this document therefore requires cloning the repository and opening the .qmd file from the repository root.\n\n**Data availability**\n\nRepository: [Paramo_SkyIslands_RootFungi](https://github.com/Ssangulo/Paramo_SkyIslands_RootFungi) \\\nSequence data: ENA accession number PRJEB107725\\\nMetadata: `Data_S1_metadata.csv, Data_S3_soil.csv`\n\n------------------------------------------------------------------------\n\n## Section 0: Setup {.unnumbered}\n\nOutput directory paths and shared aesthetic constants used throughout this document. All packages are loaded locally within each code section.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Output folders used by table/figure chunks\nout_fig_dir <- \"figures\"\nout_tab_dir <- \"tables\"\nout_obj_dir <- \"objects\"\n\n# Shared colorblind-safe palette (Wong 2011) — used in all main figures\nsite_colors <- c(BEL = \"#E69F00\", DOM = \"#009E73\", MA = \"#56B4E9\", NV = \"#D55E00\")\nsite_labels <- c(BEL = \"Belmira\", DOM = \"Las Domínguez\", MA = \"Matarredonda\", NV = \"La Nevera\")\n\n# Habitat colors (Dark2)\nhabitat_colors <- c(\"Forest\" = \"#1b9e77\", \"Subpáramo\" = \"#d95f02\", \"Páramo\" = \"#7570b3\")\n\n# Shared base theme — all main figures use theme_classic(base_size = 11)\n# (Defined per-chunk as base_theme; replicated here for reference)\n# base_theme <- theme_classic(base_size = 11) + theme(...)\n\n# Habitat label mapping (lowercase raw → display)\nlabs_map  <- c(forest = \"Forest\", subparamo = \"Subpáramo\", paramo = \"Páramo\")\nlvl_order <- c(\"Forest\", \"Subpáramo\", \"Páramo\")\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Section 1: Data and object loading {.unnumbered}\n\nAll pre-computed R objects are loaded here. Computationally intensive analyses (GLLVM, iNEXT3D, NTI/NRI, phylogeny inference) were executed on a remote server; their outputs are stored in `objects/` and loaded as needed.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Main analysis phyloseq object (root-only; replicates collapsed; soil reads removed; decontam applied)\nps_individual <- readRDS(file.path(out_obj_dir, \"ps_individual.rds\"))\n\n# Phyloseq object with phylogenetic tree (two root replicates kept separate)\ntree_ps <- readRDS(file.path(out_obj_dir, \"tree_ps.rds\"))\n\n# GLLVM heatmap plot object (generated by scripts/gllvm_analysis.R)\n# GLLVM model object fit_nb_2  too large to upload\np_heat <- readRDS(file.path(out_obj_dir, \"p_heat.rds\"))\n```\n:::\n\n\n## Section 2: Bioinformatics summary and study design\n\n### 2.1 Study sites and sampling\n\nThis study was conducted across four humid páramo regions in the Colombian Andes, spanning the Central and Eastern Cordilleras. Sampling locations covered elevations from 2,715 to 3,828 m a.s.l., representing the ecological transition from Andean forest to páramo (see main text, Fig. 1). The full sample metadata table is provided in Data_S1_metadata.csv.\n\nRoot sampling followed standardized sterile procedures. Fine roots of Gaultheria myrsinoides were excavated using a spade, and 3–5 cm root tips were clipped using a sterilized pruner. Tools were disinfected with 75% ethanol between samples, and gloves were changed between individual plants to minimize contamination. Root fragments were placed into sealed polybags stored in ice-cooled containers in the field. Samples were processed at Universidad ICESI, where roots were rinsed in sterile water to remove debris, dried briefly under a laminar flow hood, and stored at –20°C prior to shipment to Norway, and long-term storage at –80°C. Soil samples (top 15 cm) were collected at each sampling location, and five aliquots of rinse water were retained as laboratory and transport controls.\n\n**Table S1**: GPS coordinates, elevation, and vegetation type classification of the 12 sampling locations across four páramo regions. These sites span the forest–subpáramo–páramo gradient and were used for root and soil sampling. In each location, 10 root samples were collected from 5 individuals (2 root samples per individual) and 1 soil sample.\n\n|             |                      |                  |                  |                   |               |\n|------------|------------|------------|------------|------------|------------|\n| **Site ID** | **Site**             | **Altitude (m)** | **Latitude (N)** | **Longitude (W)** | **Ecosystem** |\n| NV_1        | Páramo La Nevera     | 3828             | 03º30’58.1”      | 076º03’05.4”      | Páramo        |\n| NV_2        | Páramo La Nevera     | 3550             | 03º31’37.7”      | 076º03’38.7”      | Subpáramo     |\n| NV_3        | Páramo La Nevera     | 3333             | 03º32’07.0”      | 076º04’18.3”      | Andean forest |\n| NV_4        | Páramo La Nevera     | 3078             | 03º32’48.9”      | 076º04’31.3”      | Andean forest |\n| DOM_1       | Páramo Las Domínguez | 3815             | 03º43’51.8”      | 076º06’38.1”      | Páramo        |\n| DOM_2       | Páramo Las Domínguez | 3534             | 03º44’07.2”      | 076º05’53.2”      | Subpáramo     |\n| DOM_3       | Páramo Las Domínguez | 3234             | 03º44’17.1”      | 076º05’32.9”      | Andean forest |\n| BEL_1       | Páramo Belmira       | 3254             | 06º38’43.8”      | 075º40’13.3”      | Subpáramo     |\n| BEL_2       | Páramo Belmira       | 2950             | 06º38’22.7”      | 075º39’57.3”      | Andean forest |\n| BEL_3       | Páramo Belmira       | 2715             | 06°36'55.3\"      | 075°39'51.1\"      | Andean forest |\n| MA_1        | Páramo Matarredonda  | 3678             | 04º33’31.5”      | 074º01’43.8”      | Páramo        |\n| MA_2        | Páramo Matarredonda  | 3381             | 04º33’10.3”      | 073º59’35.3”      | Subpáramo     |\n\n### 2.2 Read filtering, OTU table, and taxonomic assignment\n\nThis section provides supplementary details on sequencing read processing and quality filtering. The full bioinformatic pipeline (including DADA2 processing and replicate filtering) is available in the repository at \"/Scripts/full_pipeline_DADA2.R\". Here we report summary tables of read retention and replicate-filtering thresholds used for downstream analyses.\n\n**Table S2**: Median read numbers per PCR replicate for environmental samples (root and soil samples) and controls (blank extractions, positive, PCR blank, and tag-jump controls). The read counts are grouped at each stage of the DADA2 pipeline. Blank extraction controls (not containing any biological sample) were performed alongside real sample DNA extractions per each extraction batch. PCR blank controls contained all PCR reagents but no DNA template. Tag-jump controls are PCR reactions containing no primers and no DNA template, used to detect tag-jumping (index hopping). \n\n|                               |               |              |                         |                     |                           |\n|------------|------------|------------|------------|------------|------------|\n|                               | **Raw reads** | **Filtered** | **Merged - Non pooled** | **Merged - Pooled** | **Merged - Pseudopooled** |\n| **Root samples**              | 77,047        | 71,783       | 71,084                  | 70,343              | 71,242                    |\n| **Soil samples**              | 72,158        | 66,555       | 65,311                  | 65,498              | 65,385                    |\n| **Blank Extraction Controls** | 2,844         | 2,652        | 2,618                   | 2,566               | 2,625                     |\n| **Positive Controls**         | 95,238        | 88,174       | 88,062                  | 87,996              | 87,972                    |\n| **PCR Blank Controls**        | 291           | 261          | 250                     | 257                 | 256                       |\n| **Tag-jump Controls**         | 41            | 36           | 27                      | 30                  | 32                        |\n\n------------------------------------------------------------------------\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'knitr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: Table S3. Number of OTUs and samples after applying different replicate control filtering thresholds. The table shows results for both soil and root samples combined and only root samples.\n\n|Filtering_level    | OTU_count_soil+root| Samples_soil+root| OTU_count_root_only| Samples_root_only|\n|:------------------|-------------------:|-----------------:|-------------------:|-----------------:|\n|No filtering       |               18451|               132|               13225|               120|\n|OTU present in 2/4 |                7174|               132|                4386|               120|\n|OTU present in 3/4 |                4870|               131|                2966|               120|\n|OTU present in 4/4 |                2875|               113|                1904|               103|\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n**Table S4**: Summary of the percentage of reads and OTUS with confident taxonomic assignment at each taxonomic rank, represented by habitat. Percentages were calculated from the filtered root-only dataset (soil reads removed).\n\n|          |             |                       |                      |\n|----------|-------------|-----------------------|----------------------|\n| **Rank** | **Habitat** | **%\\_reads_assigned** | **%\\_otus_assigned** |\n| Phylum   | Forest      | 88,1                  | 88,1                 |\n| Phylum   | Subpáramo   | 91,6                  | 88,6                 |\n| Phylum   | Páramo      | 92,9                  | 89,3                 |\n| Class    | Forest      | 78,3                  | 72,5                 |\n| Class    | Subpáramo   | 84,2                  | 72,3                 |\n| Class    | Páramo      | 84,3                  | 76,0                 |\n| Order    | Forest      | 68,3                  | 59,2                 |\n| Order    | Subpáramo   | 74,2                  | 57,1                 |\n| Order    | Páramo      | 78,2                  | 60,9                 |\n| Genus    | Forest      | 32,8                  | 34,2                 |\n| Genus    | Subpáramo   | 32,1                  | 32,2                 |\n| Genus    | Páramo      | 31,4                  | 32,7                 |\n\n## Section 3: Taxonomic overview\n\n![](figures/Fig_S1_Venn.png)\n\n**Figure S1**: Venn diagram of taxonomic assignments across sampling sites, in the root only dataset, but previous to soil sequences removal. Venn diagrams illustrate the overlap of OTU taxonomic assignments across four study sites: La Nevera (NV), Las Domínguez (DOM), Belmira (BEL), and Matarredonda (MA). Only OTUs with confirmed assignments at each taxonomic level are included.\n\n------------------------------------------------------------------------\n\n![](figures/Fig_S2.png)\n\n**Figure S2**: Taxonomic composition in root samples along the elevational gradient. Relative read abundances are shown at three taxonomic ranks:  A) Phylum, B) Genus and C) Order. Each bar represents an individual root sample, grouped by habitat: Forest (2700-3300 m), Subpáramo (3300-3500 m), and Páramo (3800 m). Study sites are indicated on the y-axis.\n\n------------------------------------------------------------------------\n\n![](figures/Fig_S3.png)\n\n**Figure S3**: Taxonomic composition in soil samples, collected at each of the sampling locations. Relative read abundances are shown at three taxonomic ranks:  A) Phylum, B) Genus, and C) Order. Each bar represents an individual soil sample, grouped by habitat: Forest (2700-3300 m), Subpáramo (3300-3500 m), and Páramo (3800 m). Study sites are indicated on the y-axis.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"MicroViz code for taxonomic barplots (executed on server)\"}\n# MicroViz taxonomic barplots\n# Code executed on remote server; plots saved as PNG and embedded above.\n\nlibrary(microViz)\n\nfilter_taxa_by_rank <- function(physeq_obj, rank_prefix = \"o__\", exclude_term = \"Incertae_sedis\") {\n  taxa_assigned <- grepl(rank_prefix, tax_table(physeq_obj)[, \"Order\"])\n  exclude_incertae_sedis <- !grepl(exclude_term, tax_table(physeq_obj)[, \"Order\"])\n  taxa_filtered <- taxa_assigned & exclude_incertae_sedis\n  physeq_filtered <- prune_taxa(taxa_filtered, physeq_obj)\n  return(physeq_filtered)\n}\n\nps_filtered <- filter_taxa_by_rank(alldat.N[[2]])\n\n# Clean taxonomic prefixes like o__, g__, etc.\ntax_table(ps_filtered) <- apply(\n  tax_table(ps_filtered), 2, function(x) gsub(\"^[a-z]__\", \"\", x)\n)\n\n# Recode habitat labels\nsample_data(ps_filtered)$habitat <- dplyr::recode(\n  as.character(sample_data(ps_filtered)$habitat),\n  \"forest\"    = \"Forest\",\n  \"subparamo\" = \"Subpáramo\",\n  \"paramo\"    = \"Páramo\",\n  .default = NA_character_\n)\n\n\n# Order the factor levels\nsample_data(ps_filtered)$habitat <- factor(\n  sample_data(ps_filtered)$habitat,\n  levels = c(\"Forest\",\"Subpáramo\",\"Páramo\"),\n  ordered = TRUE\n)\n\nps_filtered <- ps_filtered %>% ps_arrange(site)\n\n#  within each site, order samples by Bray/OLO seriation at Order level ---\nsite_levels <- sample_data(ps_filtered) %>% as.data.frame() %>% pull(site) %>% unique()\n\nsamp_order <- unlist(lapply(site_levels, function(s) {\n  ps_filtered %>%\n    ps_filter(site == s) %>%\n    ps_seriate(rank = \"Order\") %>%   # same tax_level you plot\n    sample_names()                   # returns samples in seriated order\n}))\n\n# Barplot faceted by habitat, clean legend labels\np <- ps_filtered %>%\n  comp_barplot(\n    tax_level = \"Order\", n_taxa = 10, label = \"site\",\n    bar_outline_colour = \"grey5\", facet_by = \"habitat\", sample_order = samp_order,   \n    merge_other = FALSE, other_name = \"Other orders\"\n  ) +\n  coord_flip() +\n  theme(\n    legend.text  = element_text(size = 6),\n    legend.title = element_text(size = 7),\n    legend.key.size = unit(0.3, \"cm\"),\n    legend.spacing.x = unit(0.2, \"cm\"),\n    plot.title = element_text(hjust = 0.5)\n  )\n\n\n\n\n#Plot for phylum\nphy <- ps_filtered %>%\n  comp_barplot(\n    tax_level = \"Phylum\", n_taxa = 5, label = \"site\",\n    bar_outline_colour = \"grey5\", facet_by = \"habitat\", sample_order = samp_order,   \n    merge_other = FALSE, other_name = \"Other phyla\"\n  ) +\n  coord_flip() +\n  theme(\n    legend.text  = element_text(size = 6),\n    legend.title = element_text(size = 7),\n    legend.key.size = unit(0.3, \"cm\"),\n    legend.spacing.x = unit(0.2, \"cm\"),\n    plot.title = element_text(hjust = 0.5)\n  )\n\n\n\n#Plot for class\nclass <- ps_filtered %>%\n  comp_barplot(\n    tax_level = \"Class\", n_taxa = 10, label = \"site\",\n    bar_outline_colour = \"grey5\", facet_by = \"habitat\", sample_order = samp_order,   \n    merge_other = FALSE, other_name = \"Other classes\"\n  ) +\n  coord_flip() +\n  theme(\n    legend.text  = element_text(size = 6),\n    legend.title = element_text(size = 7),\n    legend.key.size = unit(0.3, \"cm\"),\n    legend.spacing.x = unit(0.2, \"cm\"),\n    plot.title = element_text(hjust = 0.5)\n  )\n\n\n\n#Plot for genus\ngenus <- ps_filtered %>%\n  comp_barplot(\n    tax_level = \"Genus\", n_taxa = 20, label = \"site\",\n    bar_outline_colour = \"grey5\", facet_by = \"habitat\", sample_order = samp_order,   \n    merge_other = FALSE, other_name = \"Other genera\"\n  ) +\n  coord_flip() +\n  theme(\n    legend.text  = element_text(size = 6),\n    legend.title = element_text(size = 7),\n    legend.key.size = unit(0.3, \"cm\"),\n    legend.spacing.x = unit(0.2, \"cm\"),\n    plot.title = element_text(hjust = 0.5)\n  )\n```\n:::\n\n\n## Section 4: Community composition {.page-break-before}\n\nThis section provides detailed statistical analyses supporting the patterns of root-associated fungal community composition described in the main text. Several of these analyses form the basis of results reported in the main manuscript; here we document the full model specifications and test statistics to ensure transparency and reproducibility.\n\nWe include distance-based redundancy analysis (dbRDA) based on robust Aitchison distances to assess habitat-associated compositional structure while conditioning on site. We further present PERMANOVA results from a balanced subset of samples (NV–DOM) used to test habitat and site effects under a controlled sampling design. In addition, we report a centroid-based turnover model quantifying the magnitude of community change across habitats using the full dataset.\n\n### 4.1 dbRDA ordination (Tables S5–S6)\n\nDistance-based redundancy analysis (dbRDA) was conducted on robust Aitchison distances to test for habitat-associated compositional structure while conditioning on site. This analysis is reported in the main manuscript as Figure 2A (habitat separation conditioned on site; permutation test $F=1.41$, $p=0.001$).\n\n------------------------------------------------------------------------\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S5. dbRDA permutation tests (by term; 999 permutations).\n\n|Component | Df| Variance|     F|    Pr|\n|:---------|--:|--------:|-----:|-----:|\n|habitat   |  2|   22.718| 1.408| 0.001|\n|Residual  | 54|  435.501|    NA|    NA|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S6. dbRDA permutation tests (by constrained axis; 999 permutations).\n\n|Axis     | Df| Variance|     F|    Pr|\n|:--------|--:|--------:|-----:|-----:|\n|CAP1     |  1|   14.579| 1.808| 0.001|\n|CAP2     |  1|    8.139| 1.009| 0.470|\n|Residual | 54|  435.501|    NA|    NA|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code used to generate Tables S5–S6 and dbRDA support plot (executed on server)\"}\n#Running dbRDA with robust aitchison\nlibrary(phyloseq)\nlibrary(vegan)\nlibrary(ggplot2)\nlibrary(knitr)\n\n\nps <- ps_individual #phyloseq object\n\nX <- as(otu_table(ps), \"matrix\")\nif (taxa_are_rows(ps)) X <- t(X)\n\nsam <- data.frame(sample_data(ps))\nsam$habitat <- factor(sam$habitat)\nsam$site    <- factor(sam$site)\n\n\n# dbRDA model: habitat constrained, conditioning on site\nd_ait <- vegdist(otu_table(ps), binary=FALSE, method=\"robust.aitchison\")\nmod_ait <- capscale(d_ait ~ habitat + Condition(site), data = sam)\n\n# Permutation tests (999 permutations)\nset.seed(1)\na_terms   <- anova.cca(mod_ait, by = \"terms\", permutations = 999)\na_axis    <- anova.cca(mod_ait, by = \"axis\", permutations = 999)\n\n\na_terms\na_axis\n\ntab_terms <- data.frame(\n  Term = rownames(a_terms),\n  Df = a_terms$Df,\n  Variance = a_terms$Variance,\n  F = a_terms$F,\n  Pr = a_terms$`Pr(>F)`,\n  row.names = NULL\n)\n\ntab_axis <- data.frame(\n  Axis = rownames(a_axis),\n  Df = a_axis$Df,\n  Variance = a_axis$Variance,\n  F = a_axis$F,\n  Pr = a_axis$`Pr(>F)`,\n  row.names = NULL\n)\n\nwrite.csv(tab_terms, file.path(out_tab_dir, \"Table_S5_dbRDA_terms.csv\"), row.names = FALSE)\nwrite.csv(tab_axis,  file.path(out_tab_dir, \"Table_S6_dbRDA_axes.csv\"),  row.names = FALSE)\n\n\n# Plotting Figure 2A support panel \neig <- mod_ait$CCA$eig\ncap1_pct <- round(100 * eig[1] / sum(eig), 1)\ncap2_pct <- round(100 * eig[2] / sum(eig), 1)\n\ncols <- c(forest=\"steelblue\", subparamo=\"seagreen3\", paramo=\"firebrick\")\n\npng(\"Figure2A_dbRDA_support.png\", width=7.2, height=6.2, units=\"in\", res=600)\npar(mar=c(4.5,4.5,1,1))\nplot(mod_ait, display=\"sites\", type=\"n\",\n     xlab=paste0(\"dbRDA1 (\",cap1_pct,\"%)\"),\n     ylab=paste0(\"dbRDA2 (\",cap2_pct,\"%)\"))\npts <- scores(mod_ait, display=\"sites\")\npoints(pts, pch=16, cex=0.7, col=cols[as.character(sam$habitat)])\nlegend(\"topright\", bty=\"n\", legend=levels(sam$habitat),\n       col=cols[levels(sam$habitat)], pch=16, pt.cex=0.9)\ndev.off()\n```\n:::\n\n\n### 4.2 PERMANOVA and beta-dispersion (Tables S7–S9)\n\nBeta-dispersion tests indicated higher within-habitat variability in forests compared with subpáramo and páramo communities (p \\< 0.001), whereas dispersion did not differ among sites (p = 0.526). Because the PERMANOVA was conducted on a balanced subset of samples, the significant effects of habitat, site, and their interaction are interpreted as reflecting genuine compositional differences rather than artifacts of unequal dispersion.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S7. PERMANOVA (adonis2) results by term.\n\n|Source       | df|  SumOfSqs|    R2| Pseudo.F| Pr..F.|\n|:------------|--:|---------:|-----:|--------:|------:|\n|site         |  1|   742.078| 0.056|    1.786|  0.001|\n|habitat      |  2|  1351.164| 0.102|    1.626|  0.001|\n|site:habitat |  2|  1241.269| 0.093|    1.493|  0.001|\n|Residual     | 24|  9974.546| 0.749|       NA|     NA|\n|Total        | 29| 13309.057| 1.000|       NA|     NA|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S8. Habitat beta-dispersion (distance to centroid). Permutation test p = 0.001.\n\n|habitat   | avg_distance_to_centroid|\n|:---------|------------------------:|\n|forest    |                   23.631|\n|paramo    |                   17.147|\n|subparamo |                   17.794|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S9. Site beta-dispersion permutation test.\n\n|test            | permutations|     F| p_value|\n|:---------------|------------:|-----:|-------:|\n|betadisper_site |          999| 0.314|   0.571|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code used to generate Tables S7–S9 (executed on server)\"}\nps <- ps_individual #phyloseq obj\n\n# Balanced subset: NV + DOM, remove NV_4\nbalanced_ps <- subset_samples(ps, site %in% c(\"DOM\", \"NV\"))\nbalanced_ps <- subset_samples(balanced_ps, site_elevation != \"NV_4\")\nbalanced_ps <- prune_taxa(taxa_sums(balanced_ps) > 0, balanced_ps)\n\n# Ensure samples are rows\nX <- as(otu_table(balanced_ps), \"matrix\")\nif (taxa_are_rows(balanced_ps)) X <- t(X)\n\nsampledf <- data.frame(sample_data(balanced_ps))\nsampledf$site    <- factor(sampledf$site)\nsampledf$habitat <- factor(sampledf$habitat)\n\n# Robust Aitchison distance\ndists <- vegdist(X, method = \"robust.aitchison\")\n\n# PERMANOVA (by terms)\nset.seed(1)\nperma <- adonis2(dists ~ site * habitat, by = \"terms\", data = sampledf, permutations = 999)\n\n# Convert output to a clean CSV table\ntab_perma <- data.frame(\n  Source   = rownames(perma),\n  df       = perma$Df,\n  SumOfSqs = perma$SumOfSqs,\n  R2       = perma$R2,\n  `Pseudo-F` = perma$F,\n  `Pr(>F)` = perma$`Pr(>F)`,\n  row.names = NULL\n)\n\n# Beta-dispersion (habitat & site)\nbd_hab  <- betadisper(dists, sampledf$habitat)\nbd_site <- betadisper(dists, sampledf$site)\n\nset.seed(1)\npt_hab  <- permutest(bd_hab,  permutations = 999)\npt_site <- permutest(bd_site, permutations = 999)\n\n# Group dispersions \ndisp_hab <- data.frame(\n  habitat = names(bd_hab$group.distances),\n  avg_distance_to_centroid = as.numeric(bd_hab$group.distances),\n  row.names = NULL\n)\n\ndisp_site <- data.frame(\n  site = names(bd_site$group.distances),\n  avg_distance_to_centroid = as.numeric(bd_site$group.distances),\n  row.names = NULL\n)\n\n\ntest_hab <- data.frame(\n  test = \"betadisper_habitat\",\n  permutations = 999,\n  F = unname(pt_hab$tab[1, \"F\"]),\n  p_value = unname(pt_hab$tab[1, \"Pr(>F)\"])\n)\n\ntest_site <- data.frame(\n  test = \"betadisper_site\",\n  permutations = 999,\n  F = unname(pt_site$tab[1, \"F\"]),\n  p_value = unname(pt_site$tab[1, \"Pr(>F)\"])\n)\n\nwrite.csv(tab_perma,  file.path(out_tab_dir, \"Table_S7_PERMANOVA.csv\"), row.names = FALSE)\nwrite.csv(disp_hab,   file.path(out_tab_dir, \"Table_S8_dispersion_habitat.csv\"), row.names = FALSE)\nwrite.csv(disp_site,  file.path(out_tab_dir, \"Table_S9_dispersion_site.csv\"), row.names = FALSE)\nwrite.csv(test_hab,   file.path(out_tab_dir, \"Table_S8_betadisper_test_habitat.csv\"), row.names = FALSE)\nwrite.csv(test_site,  file.path(out_tab_dir, \"Table_S9_betadisper_test_site.csv\"), row.names = FALSE)\n```\n:::\n\n\n### 4.3 Centroid-based turnover model (Table S10)\n\nTo quantify the magnitude of community turnover across habitats while accounting for spatial structure, we calculated the Aitchison distance of each sample to its site-specific centroid and modelled turnover as a function of habitat, site, and their interaction. Habitat had a strong effect on turnover magnitude, whereas the habitat × site interaction was not significant, indicating consistent habitat-associated turnover across geographically isolated páramo regions (Table S10).\n\nPanel B in the main manuscript Figure 2 summarizes this model (habitat $F_{2,50}=14.7$, $p<0.001$; habitat × site $F_{4,50}=1.28$, $p=0.29$), with Matarredonda (MA) shown as a dashed trend due to a compressed gradient.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S10. Linear model results for centroid-based turnover.\n\n|Effect       | df| Sum.of.Squares| Mean.Square| F.value| p.value|\n|:------------|--:|--------------:|-----------:|-------:|-------:|\n|habitat      |  2|        376.745|     188.373|  14.719|   0.000|\n|site         |  3|        138.096|      46.032|   3.597|   0.020|\n|habitat:site |  4|         65.496|      16.374|   1.279|   0.291|\n|Residuals    | 50|        639.914|      12.798|      NA|      NA|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code used to generate Table S10 (executed on server)\"}\nlibrary(phyloseq)\nlibrary(vegan)\nlibrary(ggplot2)\n\n\nps <- ps_individual #phyloseq obj\n\n\n# OTU table -> samples x taxa\nX <- as(otu_table(ps), \"matrix\")\nif (taxa_are_rows(ps)) X <- t(X)\nX <- as.matrix(X)\n\n# Robust CLR\nrfy <- decostand(X, \"rclr\", MARGIN = 1)\n\n# Metadata\nmeta <- data.frame(sample_data(ps), check.names = FALSE, stringsAsFactors = FALSE)\nstopifnot(identical(rownames(rfy), rownames(meta)))\n\n# Site centroids in CLR space\ncentroids <- rowsum(rfy, group = meta$site) / as.vector(table(meta$site))\n\n# Euclidean distance to site centroid\neuclid <- function(x, y) sqrt(sum((x - y)^2))\n\ndist_centroid <- vapply(\n  seq_len(nrow(rfy)),\n  function(i) euclid(rfy[i, ], centroids[meta$site[i], ]),\n  numeric(1)\n)\n\n# Model dataframe\ndf <- meta\ndf$dist_centroid <- dist_centroid\ndf$site <- factor(df$site)\ndf$habitat <- factor(df$habitat, levels = c(\"forest\", \"subparamo\", \"paramo\"))\n\n# Linear model (habitat-based)\nmod_hab <- lm(dist_centroid ~ habitat * site, data = df)\n\n# ANOVA table\na <- anova(mod_hab)\n\ntab_s10 <- data.frame(\n  Effect = rownames(a),\n  df = a$Df,\n  `Sum of Squares` = a$`Sum Sq`,\n  `Mean Square` = a$`Mean Sq`,\n  `F value` = a$`F value`,\n  `p value` = a$`Pr(>F)`,\n  row.names = NULL\n)\n\n# Plot centroid-based turnover: raw points + model-estimated means (95% CI)\n# Use only observed habitat-site combinations to avoid non-estimable cases.\npred <- unique(df[, c(\"habitat\", \"site\")])\npred$habitat <- factor(pred$habitat, levels = levels(df$habitat))\npred$site <- factor(pred$site, levels = levels(df$site))\npred <- pred[order(pred$site, pred$habitat), , drop = FALSE]\n\npred_fit <- predict(mod_hab, newdata = pred, se.fit = TRUE)\npred$fit <- pred_fit$fit\npred$se <- pred_fit$se.fit\nt_crit <- qt(0.975, df = df.residual(mod_hab))\npred$lower <- pred$fit - t_crit * pred$se\npred$upper <- pred$fit + t_crit * pred$se\n\ndodge <- position_dodge(width = 0.25)\n\np_turnover <- ggplot(df, aes(x = habitat, y = dist_centroid, color = site)) +\n  geom_errorbar(\n    data = pred,\n    aes(x = habitat, ymin = lower, ymax = upper, color = site, group = site),\n    width = 0.1,\n    linewidth = 0.6,\n    position = dodge,\n    inherit.aes = FALSE\n  ) +\n  geom_line(\n    data = pred,\n    aes(x = habitat, y = fit, color = site, group = site),\n    linewidth = 1,\n    position = dodge,\n    inherit.aes = FALSE\n  ) +\n  geom_point(\n    data = pred,\n    aes(x = habitat, y = fit, color = site, group = site),\n    size = 2.3,\n    position = dodge,\n    inherit.aes = FALSE\n  ) +\n  labs(\n    x = \"Habitat\",\n    y = \"Distance to site centroid (Aitchison CLR space)\",\n    color = \"Site\"\n  ) +\n  theme_bw(base_size = 11)\n\np_turnover\n\n# export\nggsave(\n  filename = file.path(out_fig_dir, \"Figure2B_centroid_turnover_support.png\"),\n  plot = p_turnover,\n  width = 8.5,\n  height = 5,\n  dpi = 900,\n  bg = \"white\"\n)\n\nwrite.csv(tab_s10, file.path(out_tab_dir, \"Table_S10_centroid_model.csv\"), row.names = FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code used to generate Figure 2 (dbRDA + centroid turnover, executed on server)\"}\n# =============================================================================\n# Figure 2: Community composition (dbRDA) + Centroid-based turnover model\n# Two-panel publication figure for Molecular Ecology submission\n# =============================================================================\n\nlibrary(ggplot2)\nlibrary(patchwork)\nlibrary(ggrepel)\nlibrary(dplyr)\n\n# -----------------------------------------------------------------------------\n# SHARED AESTHETICS\n# -----------------------------------------------------------------------------\n\n# Colorblind-safe palette (Wong 2011)\nsite_colors <- c(\n  BEL = \"#E69F00\",\n  DOM = \"#009E73\",\n  MA  = \"#56B4E9\",\n  NV  = \"#D55E00\"\n)\n\nsite_labels <- c(\n  BEL = \"Belmira\",\n  DOM = \"Las Domínguez\",\n  MA  = \"Matarredonda\",\n  NV  = \"La Nevera\"\n)\n\nbase_theme <- theme_classic(base_size = 11) +\n  theme(\n    axis.title      = element_text(size = 9),\n    axis.text       = element_text(size = 7, color = \"black\"),\n    legend.title    = element_text(size = 5, face = \"bold\"),\n    legend.text     = element_text(size = 4.5),\n    legend.key.size = unit(0.6, \"lines\"),\n    legend.position = \"right\",\n    plot.tag        = element_text(size = 13, face = \"bold\"),\n    strip.background = element_blank()\n  )\n\n# -----------------------------------------------------------------------------\n# PANEL A: dbRDA ordination\n# Uses mod_ait (capscale object) and sam (metadata) from the dbRDA section\n# -----------------------------------------------------------------------------\n\nscores_sites <- as.data.frame(scores(mod_ait, display = \"sites\", choices = 1:2))\nscores_sites$SampleID <- rownames(scores_sites)\n\nmeta_join <- data.frame(\n  SampleID = rownames(sam),\n  site     = as.character(sam$site),\n  habitat  = as.character(sam$habitat),\n  stringsAsFactors = FALSE\n)\n\nscores_sites <- scores_sites %>%\n  left_join(meta_join, by = \"SampleID\")\n\n# Recode habitat labels and add accent to Subpáramo/Páramo\nscores_sites$habitat <- factor(\n  scores_sites$habitat,\n  levels = c(\"Forest\", \"Subparamo\", \"Paramo\"),\n  labels = c(\"Forest\", \"Subpáramo\", \"Páramo\")\n)\nscores_sites$site <- factor(scores_sites$site, levels = names(site_colors))\n\n# Variance explained\neig      <- eigenvals(mod_ait)\nprop_exp <- eig / sum(eig[eig > 0])\ncap1_pct <- round(prop_exp[\"CAP1\"] * 100, 1)\ncap2_pct <- round(prop_exp[\"CAP2\"] * 100, 1)\n\nhab_centroids <- scores_sites %>%\n  group_by(habitat) %>%\n  summarise(CAP1 = mean(CAP1), CAP2 = mean(CAP2), .groups = \"drop\")\n\npanel_A <- ggplot(scores_sites, aes(x = CAP1, y = CAP2)) +\n  geom_point(\n    aes(color = site, shape = habitat),\n    size = 1.4, alpha = 0.75, stroke = 0.3\n  ) +\n  geom_point(\n    data = hab_centroids,\n    aes(shape = habitat),\n    color = \"black\", size = 2.8, fill = \"white\", stroke = 1.0\n  ) +\n  geom_text_repel(\n    data        = hab_centroids,\n    aes(label   = habitat),\n    color       = \"black\", size = 2.4, fontface = \"italic\",\n    box.padding = 0.4, min.segment.length = 0.2\n  ) +\n  scale_color_manual(values = site_colors, labels = site_labels, name = \"Site\") +\n  scale_shape_manual(\n    values = c(\"Forest\" = 16, \"Subpáramo\" = 17, \"Páramo\" = 15),\n    name   = \"Habitat\"\n  ) +\n  labs(\n    x   = paste0(\"dbRDA1 (\", cap1_pct, \"%)\"),\n    y   = paste0(\"dbRDA2 (\", cap2_pct, \"%)\"),\n    tag = \"A\"\n  ) +\n  base_theme +\n  theme(\n    legend.position = \"none\",\n    axis.title      = element_text(size = 8.5)\n  )\n\n# -----------------------------------------------------------------------------\n# PANEL B: Centroid-based turnover model\n# Uses mod_hab and df from the centroid model section\n# MA flagged with dashed line (incomplete gradient — no forest baseline)\n# -----------------------------------------------------------------------------\n\npred <- unique(df[, c(\"habitat\", \"site\")])\npred$habitat <- factor(pred$habitat, levels = c(\"forest\", \"subparamo\", \"paramo\"))\npred$site    <- factor(pred$site,    levels = names(site_colors))\npred <- pred[order(pred$site, pred$habitat), , drop = FALSE]\n\npred_fit   <- predict(mod_hab, newdata = pred, se.fit = TRUE)\npred$fit   <- pred_fit$fit\npred$se    <- pred_fit$se.fit\nt_crit     <- qt(0.975, df = df.residual(mod_hab))\npred$lower <- pred$fit - t_crit * pred$se\npred$upper <- pred$fit + t_crit * pred$se\n\npred$linetype_group <- ifelse(pred$site == \"MA\", \"incomplete\", \"complete\")\ndf$linetype_group   <- ifelse(df$site   == \"MA\", \"incomplete\", \"complete\")\n\npred$habitat_lab <- factor(pred$habitat,\n  levels = c(\"forest\", \"subparamo\", \"paramo\"),\n  labels = c(\"Forest\", \"Subpáramo\", \"Páramo\"))\ndf$habitat_lab <- factor(df$habitat,\n  levels = c(\"forest\", \"subparamo\", \"paramo\"),\n  labels = c(\"Forest\", \"Subpáramo\", \"Páramo\"))\n\npred$site_fac <- factor(pred$site, levels = names(site_colors))\ndf$site_fac   <- factor(df$site,   levels = names(site_colors))\n\ndodge <- position_dodge(width = 0.3)\n\npanel_B <- ggplot() +\n  geom_jitter(\n    data = df,\n    aes(x = habitat_lab, y = dist_centroid, color = site_fac),\n    width = 0.08, height = 0, size = 1.6, alpha = 0.35, show.legend = FALSE\n  ) +\n  geom_line(\n    data = pred,\n    aes(x = habitat_lab, y = fit, color = site_fac,\n        group = site_fac, linetype = linetype_group),\n    linewidth = 1.0, position = dodge\n  ) +\n  geom_errorbar(\n    data = pred,\n    aes(x = habitat_lab, ymin = lower, ymax = upper,\n        color = site_fac, group = site_fac),\n    width = 0.08, linewidth = 0.55, position = dodge\n  ) +\n  geom_point(\n    data = pred,\n    aes(x = habitat_lab, y = fit, color = site_fac, group = site_fac),\n    size = 2.8, position = dodge\n  ) +\n  scale_color_manual(values = site_colors, labels = site_labels, name = \"Site\") +\n  scale_linetype_manual(\n    values = c(complete = \"solid\", incomplete = \"dashed\"),\n    guide  = \"none\"\n  ) +\n  labs(\n    x   = \"Habitat\",\n    y   = \"Distance to site centroid\",\n    tag = \"B\"\n  ) +\n  base_theme +\n  theme(legend.position = \"right\") +\n  guides(color = guide_legend(override.aes = list(size = 2, linewidth = 0.8)))\n\n# -----------------------------------------------------------------------------\n# COMBINE with patchwork\n# -----------------------------------------------------------------------------\n\nfig2 <- panel_A + panel_B +\n  plot_layout(ncol = 2, widths = c(0.9, 1.1), guides = \"collect\")\n\nggsave(\n  filename = file.path(out_fig_dir, \"Figure_2_dbRDA_centroid.png\"),\n  plot = fig2, width = 17.4, height = 6.3, units = \"cm\", dpi = 900, bg = \"white\"\n)\n```\n:::\n\n\n### 4.4 Figure 2\n\n![](figures/Figure_2_dbRDA_centroid.png)\n\n**Figure 2**: Community composition and turnover across habitats. Panel A: dbRDA ordination of RAF communities conditioned on site (color = site, shape = habitat; permutation $F=1.41$, $p=0.001$). Panel B: centroid-based turnover model (distance to site-specific centroid across habitats), with MA shown as dashed due to incomplete gradient (habitat $F_{2,50}=14.7$, $p<0.001$; habitat × site $F_{4,50}=1.28$, $p=0.29$).\n\n## Section 5: Diversity trajectories {.page-break-before}\n\nDiversity trajectories were assessed using three complementary approaches: per-sample Hill diversity models to test parallelism across sites, iNEXT3D rarefaction/extrapolation curves for habitat-level estimates, and beta-diversity partitioning. All analyses require a rooted phylogenetic tree, inferred below. Analyses are presented in computation order; Figure 3 follows as a composite of pre-computed outputs.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Phylogenetic tree inference (GTR+Γ; executed on server)\"}\nlibrary(DECIPHER)\nlibrary(Biostrings)\nlibrary(phangorn)\nlibrary(phyloseq)\n\n# alldat.N[[2]]: rg2-filtered nopool root object retaining both\n# root replicates per plant (120 samples); used for phylogenetic\n# tree inference only. Equivalent to rg2.nopoolps before\n# per-plant collapsing (ps_individual).\nalign <- AlignSeqs(DNAStringSet(refseq(alldat.N[[2]])), anchor=NA)\n\nphang_align <- phyDat(as(align, \"matrix\"), type=\"DNA\")\ndm <- dist.ml(phang_align)\ntreeNJ <- NJ(dm)\nfit <- pml(treeNJ, data=phang_align)\nfitGTR <- update(fit, k=4, inv=0.2)\nfit <- optim.pml(fitGTR, model=\"GTR\", optInv=TRUE, optGamma=TRUE, optNni=FALSE,\n                 optBf=TRUE, optQ=TRUE, optEdge=TRUE, optRooted=FALSE,\n                 rearrangement = \"stochastic\", control = pml.control(trace = 0))\n\ntree_data_rg2.N <- merge_phyloseq(alldat.N[[2]], fit$tree)\n\n# Save for downstream use (loaded in Section 1 as tree_ps)\nsaveRDS(tree_data_rg2.N, file.path(out_obj_dir, \"tree_ps.rds\"))\n```\n:::\n\n\n### 5.1 Per-sample Hill diversity: parallelism models (Tables S18–S19)\n\nTo evaluate whether diversity trajectories are parallel across geographically isolated sites, we model diversity as a function of habitat (ordered along elevation), site, and their interaction. The key term is habitat × site: a weak/non-significant interaction with a strong habitat main effect supports broadly parallel trajectories with site-specific baselines.\n\nFor this section, diversity is computed independently for each sample using Hill numbers: taxonomic diversity (TD) and phylogenetic diversity (PD) at q = 1 (effective Shannon) as the primary metric. This preserves interpretability, keeps consistency with Hill-number logic, and allows direct sample-level inference on trajectory parallelism.\n\nWe use a two-model strategy: (i) a primary habitat-factor model for ecological interpretation, and (ii) a secondary numeric-trend model (ordered habitat steps) to summarize site-specific slopes. Model family is screened first (Gaussian, log-Gaussian, Gamma-log) before final inference.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S18. ANOVA table for the log-linear model of per-sample taxonomic diversity (TD; Hill q=1) as a function of habitat, site, and their interaction. Habitat × site interaction F(4,50)=1.52, p=0.21 supports parallel diversity trajectories across sites.\n\n|Term         | Df| Sum.Sq| Mean.Sq| F.value| Pr..F.|\n|:------------|--:|------:|-------:|-------:|------:|\n|habitat      |  2|  2.748|   1.374|   4.395|  0.017|\n|site         |  3|  0.633|   0.211|   0.675|  0.571|\n|habitat:site |  4|  1.899|   0.475|   1.518|  0.211|\n|Residuals    | 50| 15.633|   0.313|      NA|     NA|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S19. ANOVA table for the log-linear model of per-sample phylogenetic diversity (PD; Hill q=1, meanPD) as a function of habitat, site, and their interaction. Habitat × site interaction F(4,50)=1.22, p=0.31 supports parallel diversity trajectories across sites.\n\n|Term         | Df| Sum.Sq| Mean.Sq| F.value| Pr..F.|\n|:------------|--:|------:|-------:|-------:|------:|\n|habitat      |  2|  1.135|   0.568|   3.027|  0.057|\n|site         |  3|  0.794|   0.265|   1.411|  0.251|\n|habitat:site |  4|  0.918|   0.230|   1.224|  0.313|\n|Residuals    | 50|  9.375|   0.188|      NA|     NA|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Per-sample Hill TD/PD: family checks + primary factor model + secondary slope model\"}\nlibrary(phyloseq)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(ape)\nlibrary(phangorn)\nlibrary(hillR)\nlibrary(emmeans)\n\n# Inputs\nps_ind  <- ps_individual   # collapsed replicates\nps_tree <- tree_ps         # object that already has phylogeny\n\nstopifnot(inherits(ps_ind, \"phyloseq\"), inherits(ps_tree, \"phyloseq\"))\nstopifnot(!is.null(phy_tree(ps_tree, errorIfNULL = FALSE)))\n\n# 1) Match taxa between ps_ind and tree_ps tree\ntaxa_ind  <- taxa_names(ps_ind)\ntips_tree <- phy_tree(ps_tree)$tip.label\ncommon_taxa <- intersect(taxa_ind, tips_tree)\n\n# 2) Prune collapsed object to taxa represented in tree and build matching tree\nps_div <- prune_taxa(common_taxa, ps_ind)\n\ntr_ind <- ape::keep.tip(phy_tree(ps_tree), common_taxa)\ntr_ind$node.label <- NULL\nif (!ape::is.rooted(tr_ind)) tr_ind <- phangorn::midpoint(tr_ind)\n\n# Reorder OTU taxa to match tree tip order (important)\nps_div <- prune_taxa(tr_ind$tip.label, ps_div)\nstopifnot(identical(taxa_names(ps_div), tr_ind$tip.label))\n\n# 3) Attach tree to collapsed object\nphy_tree(ps_div) <- tr_ind\nvalidObject(ps_div)\n\nmeta <- as(sample_data(ps_div), \"data.frame\")\nmeta$SampleID <- rownames(meta)\nmeta$site <- factor(meta$site)\nmeta$habitat <- factor(\n  meta$habitat,\n  levels = c(\"forest\", \"subparamo\", \"paramo\"),\n  ordered = TRUE\n)\nmeta$habitat_num <- as.numeric(meta$habitat)\n\n# OTU matrix as taxa x samples -> comm as samples x taxa\nOTU <- as(otu_table(ps_div), \"matrix\")\nif (!taxa_are_rows(ps_div)) OTU <- t(OTU)\ncomm <- t(OTU)\nmeta$lib_size <- sample_sums(ps_div)\n\n# Tree/community alignment is already defined above via ps_div + tr_ind\ntr2 <- phy_tree(ps_div)\ncomm2 <- comm[, taxa_names(ps_div), drop = FALSE]\n\n# Alignment checks\nstopifnot(identical(colnames(comm2), tr2$tip.label))\nstopifnot(!anyDuplicated(colnames(comm2)))\n\n# Compatibility wrappers for hillR argument names across versions\nget_hill_taxa <- function(x, qval = 1) {\n  out <- tryCatch(hill_taxa(x, q = qval), error = function(e) NULL)\n  if (is.null(out)) out <- hill_taxa(x, qvalue = qval)\n  as.numeric(out)\n}\n\nget_hill_phylo <- function(x, tree, qval = 1) {\n  out <- tryCatch(hill_phylo(x, tree = tree, q = qval), error = function(e) NULL)\n  if (is.null(out)) out <- tryCatch(hill_phylo(x, tree, q = qval), error = function(e) NULL)\n  if (is.null(out)) out <- tryCatch(hill_phylo(x, tree = tree, qvalue = qval), error = function(e) NULL)\n  if (is.null(out)) out <- hill_phylo(x, tree, qvalue = qval)\n  as.numeric(out)\n}\n\n# Primary metrics (q = 1): independent values per sample\nmeta$TD_q1 <- get_hill_taxa(comm, qval = 1)\nmeta$PD_q1 <- get_hill_phylo(comm2, tree = tr2, qval = 1)\n\n# Optional sensitivity metrics for supplementary checks (not modeled by default)\nmeta$TD_q0 <- get_hill_taxa(comm, qval = 0)\nmeta$TD_q2 <- get_hill_taxa(comm, qval = 2)\nmeta$PD_q0 <- get_hill_phylo(comm2, tree = tr2, qval = 0)\nmeta$PD_q2 <- get_hill_phylo(comm2, tree = tr2, qval = 2)\n\n# Ensure tabular class for dplyr/tidyr verbs\nmeta <- as.data.frame(meta, stringsAsFactors = FALSE)\n\ndiv_long <- meta %>%\n  dplyr::select(SampleID, site, habitat, habitat_num, TD_q1, PD_q1) %>%\n  pivot_longer(\n    cols = c(TD_q1, PD_q1),\n    names_to = \"metric\",\n    values_to = \"estimate\"\n  ) %>%\n  dplyr::mutate(metric = dplyr::recode(metric, TD_q1 = \"TD (q=1)\", PD_q1 = \"PD (q=1)\"))\n\n# Optional depth sensitivity covariate\nif (!\"lib_size\" %in% names(meta)) {\n  meta$lib_size <- as.numeric(sample_sums(ps_div)[meta$SampleID])\n}\n\ndiv_long <- div_long %>%\n  dplyr::left_join(meta[, c(\"SampleID\", \"lib_size\"), drop = FALSE], by = \"SampleID\")\n\n# ---------- 1) Family screening before final inference ----------\n# Candidate families:\n#  - gaussian:      estimate ~ ...\n#  - lognormal_lm:  log(estimate) ~ ...\n#  - gamma_log:     glm(..., family = Gamma(link = \"log\"))\n\nfit_candidates <- function(dat, rhs_formula) {\n  out <- list()\n  out$gaussian <- lm(rhs_formula, data = dat)\n  out$lognormal_lm <- lm(update(rhs_formula, log(estimate) ~ .), data = dat)\n  out$gamma_log <- glm(rhs_formula, data = dat, family = Gamma(link = \"log\"))\n  out\n}\n\nsummarize_candidates <- function(fits, metric_label, model_type) {\n  data.frame(\n    metric = metric_label,\n    model_type = model_type,\n    family = names(fits),\n    AIC = vapply(fits, AIC, numeric(1)),\n    stringsAsFactors = FALSE\n  )\n}\n\ntd_dat <- filter(div_long, metric == \"TD (q=1)\")\npd_dat <- filter(div_long, metric == \"PD (q=1)\")\n\ntd_cand_factor <- fit_candidates(td_dat, estimate ~ habitat * site)\npd_cand_factor <- fit_candidates(pd_dat, estimate ~ habitat * site)\n\ntd_cand_num <- fit_candidates(td_dat, estimate ~ habitat_num * site)\npd_cand_num <- fit_candidates(pd_dat, estimate ~ habitat_num * site)\n\nmodel_screen <- bind_rows(\n  summarize_candidates(td_cand_factor, \"TD (q=1)\", \"factor\"),\n  summarize_candidates(pd_cand_factor, \"PD (q=1)\", \"factor\"),\n  summarize_candidates(td_cand_num, \"TD (q=1)\", \"numeric\"),\n  summarize_candidates(pd_cand_num, \"PD (q=1)\", \"numeric\")\n) %>%\n  arrange(metric, model_type, AIC)\n\nmodel_screen\n\n# Simple residual checks for the top candidate families\npar(mfrow = c(2, 2))\nplot(td_cand_factor$lognormal_lm, main = \"TD factor: lognormal_lm\")\nplot(pd_cand_factor$lognormal_lm, main = \"PD factor: lognormal_lm\")\nplot(td_cand_num$lognormal_lm, main = \"TD numeric: lognormal_lm\")\nplot(pd_cand_num$lognormal_lm, main = \"PD numeric: lognormal_lm\")\npar(mfrow = c(1, 1))\n\n# ---------- 2) Final models (set after reviewing model_screen + residuals) ----------\n# Best model is lognormal_lm by far\nselected_family_td <- \"lognormal_lm\"\nselected_family_pd <- \"lognormal_lm\"\n\npick_fit <- function(fit_list, selected_name) {\n  fit_list[[selected_name]]\n}\n\n# Primary ecological model: habitat as factor\nm_td_factor <- pick_fit(td_cand_factor, selected_family_td)\nm_pd_factor <- pick_fit(pd_cand_factor, selected_family_pd)\n\n# Secondary slope model: habitat ordered as numeric\nm_td_num <- pick_fit(td_cand_num, selected_family_td)\nm_pd_num <- pick_fit(pd_cand_num, selected_family_pd)\n\n# ANOVA tables\nanova_td_factor <- anova(m_td_factor)\nanova_pd_factor <- anova(m_pd_factor)\nanova_td_num <- anova(m_td_num)\nanova_pd_num <- anova(m_pd_num)\n\nanova_td_factor\nanova_pd_factor\nanova_td_num\nanova_pd_num\n\n# Primary inference (factor model): marginal means + habitat contrasts within each site\nemm_td <- emmeans(m_td_factor, ~ habitat | site) %>% summary(infer = c(TRUE, TRUE))\nemm_pd <- emmeans(m_pd_factor, ~ habitat | site) %>% summary(infer = c(TRUE, TRUE))\n\ncontr_td <- contrast(emmeans(m_td_factor, ~ habitat | site), method = \"pairwise\") %>%\n  summary(infer = c(TRUE, TRUE), adjust = \"holm\")\ncontr_pd <- contrast(emmeans(m_pd_factor, ~ habitat | site), method = \"pairwise\") %>%\n  summary(infer = c(TRUE, TRUE), adjust = \"holm\")\n\n# Secondary inference (numeric model): site-specific slopes\nslopes_td <- emtrends(m_td_num, ~ site, var = \"habitat_num\") %>%\n  summary(infer = c(TRUE, TRUE))\nslopes_pd <- emtrends(m_pd_num, ~ site, var = \"habitat_num\") %>%\n  summary(infer = c(TRUE, TRUE))\n\n# Predicted means at habitat steps from numeric model (consistent with habitat_num)\nemm_td_num_steps <- emmeans(m_td_num, ~ site | habitat_num,\n                            at = list(habitat_num = c(1, 2, 3))) %>%\n  summary(infer = c(TRUE, TRUE))\nemm_pd_num_steps <- emmeans(m_pd_num, ~ site | habitat_num,\n                            at = list(habitat_num = c(1, 2, 3))) %>%\n  summary(infer = c(TRUE, TRUE))\n\nemm_td\nemm_pd\ncontr_td\ncontr_pd\nslopes_td\nslopes_pd\nemm_td_num_steps\nemm_pd_num_steps\n\n# ---------- 3) Plot (factor model means/CI + observed values) ----------\nemm_td_plot <- as.data.frame(\n  summary(\n    emmeans(m_td_factor, ~ habitat | site),\n    infer = c(TRUE, TRUE),\n    type = \"response\",\n    bias.adjust = TRUE\n  )\n) %>%\n  dplyr::mutate(metric = \"TD (q=1)\")\n\nemm_pd_plot <- as.data.frame(\n  summary(\n    emmeans(m_pd_factor, ~ habitat | site),\n    infer = c(TRUE, TRUE),\n    type = \"response\",\n    bias.adjust = TRUE\n  )\n) %>%\n  dplyr::mutate(metric = \"PD (q=1)\")\n\nemm_plot <- dplyr::bind_rows(emm_td_plot, emm_pd_plot) %>%\n  dplyr::mutate(\n    habitat = factor(habitat, levels = levels(meta$habitat), ordered = TRUE),\n    site = factor(site, levels = levels(meta$site))\n  )\n\n# emmeans column names vary by model/link; standardize for plotting\nif (!\"response\" %in% names(emm_plot) && \"emmean\" %in% names(emm_plot)) {\n  emm_plot$response <- emm_plot$emmean\n}\nif (!\"lower.CL\" %in% names(emm_plot) && \"asymp.LCL\" %in% names(emm_plot)) {\n  emm_plot$lower.CL <- emm_plot$asymp.LCL\n}\nif (!\"upper.CL\" %in% names(emm_plot) && \"asymp.UCL\" %in% names(emm_plot)) {\n  emm_plot$upper.CL <- emm_plot$asymp.UCL\n}\n\n# Force original-scale plotting when lognormal models are used and emmeans\n# returns only link-scale columns (no explicit response-scale columns).\nif (\n  \"emmean\" %in% names(emm_plot) &&\n  !(\"response\" %in% names(emm_td_plot) && \"response\" %in% names(emm_pd_plot))\n) {\n  is_log_td <- emm_plot$metric == \"TD (q=1)\" & selected_family_td == \"lognormal_lm\"\n  is_log_pd <- emm_plot$metric == \"PD (q=1)\" & selected_family_pd == \"lognormal_lm\"\n  is_log_any <- is_log_td | is_log_pd\n\n  emm_plot$response[is_log_any] <- exp(emm_plot$emmean[is_log_any])\n  emm_plot$lower.CL[is_log_any] <- exp(emm_plot$lower.CL[is_log_any])\n  emm_plot$upper.CL[is_log_any] <- exp(emm_plot$upper.CL[is_log_any])\n}\n\n# Observed summaries for sanity checks against model-estimated values\nobs_summary <- div_long %>%\n  dplyr::group_by(metric, site, habitat) %>%\n  dplyr::summarise(\n    n = dplyr::n(),\n    obs_mean = mean(estimate, na.rm = TRUE),\n    obs_median = median(estimate, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nplot_check <- emm_plot %>%\n  dplyr::select(metric, site, habitat, response, lower.CL, upper.CL) %>%\n  dplyr::left_join(obs_summary, by = c(\"metric\", \"site\", \"habitat\"))\n\nplot_check\n\nmodel_dodge <- position_dodge(width = 0.22)\n\np_div_traj <- ggplot(div_long, aes(x = habitat, y = estimate, color = site)) +\n  geom_point(\n    position = position_jitter(width = 0.08, height = 0),\n    alpha = 0.55,\n    size = 1.6\n  ) +\n  geom_errorbar(\n    data = emm_plot,\n    aes(x = habitat, ymin = lower.CL, ymax = upper.CL, color = site, group = site),\n    width = 0.12,\n    linewidth = 0.6,\n    position = model_dodge,\n    inherit.aes = FALSE\n  ) +\n  geom_line(\n    data = emm_plot,\n    aes(x = habitat, y = response, color = site, group = site),\n    linewidth = 1.2,\n    position = model_dodge,\n    inherit.aes = FALSE\n  ) +\n  geom_point(\n    data = emm_plot,\n    aes(x = habitat, y = response, color = site, group = site),\n    size = 2.5,\n    position = model_dodge,\n    inherit.aes = FALSE\n  ) +\n  facet_wrap(~ metric, scales = \"free_y\", nrow = 1) +\n  labs(\n    x = \"Habitat\",\n    y = \"Per-sample Hill diversity\"\n  ) +\n  theme_bw(base_size = 11)\n\np_div_traj\n\n# Optional export\nwrite.csv(as.data.frame(anova_td_factor), file.path(out_tab_dir, \"Table_S18_TD_parallelism_anova.csv\"), row.names = FALSE)\nwrite.csv(as.data.frame(anova_pd_factor), file.path(out_tab_dir, \"Table_S19_PD_parallelism_anova.csv\"), row.names = FALSE)\n\n\nggsave(\n  filename = file.path(out_fig_dir, \"Fig_x_TD_PD_parallel_trajectories.png\"),\n  plot = p_div_traj,\n  width = 10,\n  height = 5.5,\n  dpi = 900,\n  bg = \"white\"\n)\n```\n:::\n\n\n### 5.2 iNEXT3D rarefaction curves and asymptotic diversity summaries (Tables S16–S17)\n\nWe quantified habitat-associated patterns in taxonomic diversity (TD) and phylogenetic diversity (PD) using iNEXT3D and Hill numbers (q = 0, 1, 2). Diversity estimates were computed from incidence (presence/absence) matrices at the habitat level and evaluated under rarefaction/extrapolation with bootstrap confidence intervals (nboot = 500). Phylogenetic diversity was estimated as meanPD using a pruned phylogeny matched to the observed taxa. The combined curve visualization is presented in main-text Figure 3A; asymptotic summaries are provided in Tables S16–S17, and the per-sample parallelism ANOVA results in Tables S18–S19.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S16. Taxonomic diversity (TD) summary from iNEXT3D across habitats (q = 0, 1, 2; nboot = 500). Observed and asymptotic estimates are reported with standard errors, 95% confidence intervals, and sample coverage at observed effort and at double effort.\n\n|Assemblage |qTD               |   TD_obs|   TD_asy|    s.e.|  qTD.LCL|  qTD.UCL|\n|:----------|:-----------------|--------:|--------:|-------:|--------:|--------:|\n|Forest     |Species richness  | 2521.000| 4581.983| 125.848| 4335.326| 4828.640|\n|Forest     |Shannon diversity | 1810.823| 2927.463|  51.242| 2827.030| 3027.896|\n|Forest     |Simpson diversity | 1158.528| 1467.726|  34.168| 1400.758| 1534.695|\n|Páramo     |Species richness  |  901.000| 1945.702|  95.214| 1759.086| 2132.317|\n|Páramo     |Shannon diversity |  693.768| 1316.325|  43.456| 1231.153| 1401.497|\n|Páramo     |Simpson diversity |  474.571|  661.005|  30.584|  601.061|  720.948|\n|Subpáramo  |Species richness  | 1533.000| 3059.820| 108.142| 2847.866| 3271.775|\n|Subpáramo  |Shannon diversity | 1225.295| 2341.860|  58.351| 2227.494| 2456.226|\n|Subpáramo  |Simpson diversity |  846.718| 1247.075|  49.323| 1150.403| 1343.747|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S17. Phylogenetic diversity (PD; meanPD) summary from iNEXT3D across habitats (q = 0, 1, 2; nboot = 500), including coverage and effective lineage estimates under rarefaction/extrapolation.\n\n|Habitat   |qPD      |  PD_obs|  PD_asy|  s.e.| qPD.LCL| qPD.UCL| Reftime|Type   |\n|:---------|:--------|-------:|-------:|-----:|-------:|-------:|-------:|:------|\n|Forest    |q = 0 PD | 185.553| 283.343| 7.643| 268.362| 298.324|   0.873|meanPD |\n|Forest    |q = 1 PD |  96.045| 115.843| 1.427| 113.045| 118.641|   0.873|meanPD |\n|Forest    |q = 2 PD |  53.644|  56.697| 0.585|  55.551|  57.842|   0.873|meanPD |\n|Páramo    |q = 0 PD |  81.971| 134.076| 6.501| 121.334| 146.818|   0.873|meanPD |\n|Páramo    |q = 1 PD |  46.984|  60.900| 1.321|  58.310|  63.489|   0.873|meanPD |\n|Páramo    |q = 2 PD |  27.101|  29.356| 0.529|  28.320|  30.392|   0.873|meanPD |\n|Subpáramo |q = 0 PD | 132.936| 213.016| 7.909| 197.514| 228.518|   0.873|meanPD |\n|Subpáramo |q = 1 PD |  75.157|  98.360| 1.843|  94.748| 101.973|   0.873|meanPD |\n|Subpáramo |q = 2 PD |  39.842|  43.233| 0.715|  41.831|  44.635|   0.873|meanPD |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"iNEXT3D diversity analyses (executed on remote server)\"}\nlibrary(phyloseq)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(iNEXT.3D)\nlibrary(ape)\nlibrary(knitr)\nlibrary(phangorn)\n\n# NOTE: The phylogenetic tree is loaded from tree_ps (objects/tree_ps.rds).\n# The GTR inference block below is REDUNDANT — tree_ps already contains the fitted tree.\n# REMOVE the AlignSeqs/optim.pml block if re-running; use phy_tree(tree_ps) directly.\n\nset.seed(1)\n\nlabs_map  <- c(forest = \"Forest\", subparamo = \"Subpáramo\", paramo = \"Páramo\")\nlvl_order <- c(\"Forest\", \"Subpáramo\", \"Páramo\")\n\nrelabel_inext <- function(x) {\n  f <- function(df){\n    if (!(\"Assemblage\" %in% names(df))) return(df)\n    df$Assemblage <- as.character(df$Assemblage)\n    df$Assemblage <- labs_map[df$Assemblage]\n    df$Assemblage <- factor(df$Assemblage, levels = lvl_order)\n    df\n  }\n  x$TDInfo   <- f(as.data.frame(x$TDInfo))\n  x$TDAsyEst <- f(as.data.frame(x$TDAsyEst))\n  if (!is.null(x$TDiNextEst)) {\n    for (nm in names(x$TDiNextEst)) x$TDiNextEst[[nm]] <- f(as.data.frame(x$TDiNextEst[[nm]]))\n  }\n  x\n}\n\nps_td <- tree_ps\n\nsd <- as.data.frame(sample_data(ps_td))\n\nOTU <- as(otu_table(ps_td), \"matrix\")\nif (!taxa_are_rows(ps_td)) OTU <- t(OTU)\n\ninc_by_hab_td <- lapply(split(rownames(sd), sd$habitat), function(samps){\n  M <- OTU[, colnames(OTU) %in% samps, drop = FALSE]\n  M[M > 0] <- 1\n  storage.mode(M) <- \"numeric\"\n  M\n})\n\ninc_by_hab_td <- inc_by_hab_td[names(inc_by_hab_td) %in% names(labs_map)]\ninc_by_hab_td <- inc_by_hab_td[vapply(inc_by_hab_td, function(M) nrow(M) > 0 && ncol(M) > 0, TRUE)]\n\nout_TD <- iNEXT3D(data = inc_by_hab_td, diversity = \"TD\", q = c(0,1,2),\n                  datatype = \"incidence_raw\", nboot = 500)\nout_TD <- relabel_inext(out_TD)\n\ntab_s16 <- as.data.frame(out_TD$TDAsyEst) %>%\n  mutate(Diversity_order = case_when(\n    qTD == 0 ~ \"Species richness\", qTD == 1 ~ \"Shannon diversity\",\n    qTD == 2 ~ \"Simpson diversity\", TRUE ~ as.character(qTD)\n  )) %>%\n  rename(Habitat = Assemblage)\n\nwrite.csv(tab_s16, file.path(out_tab_dir, \"Table_S16_iNEXT3D_TD.csv\"), row.names = FALSE)\n\nps_pd <- tree_ps\nsd2 <- as.data.frame(sample_data(ps_pd))\n\nX <- as(otu_table(ps_pd), \"matrix\")\nif (!taxa_are_rows(ps_pd)) X <- t(X)\n\ninc_by_hab_pd <- lapply(split(rownames(sd2), sd2$habitat), function(samps){\n  M <- X[, colnames(X) %in% samps, drop = FALSE]\n  M[M > 0] <- 1; storage.mode(M) <- \"numeric\"; M\n})\ninc_by_hab_pd <- inc_by_hab_pd[names(inc_by_hab_pd) %in% names(labs_map)]\ninc_by_hab_pd <- inc_by_hab_pd[vapply(inc_by_hab_pd, function(M) nrow(M) > 0 && ncol(M) > 0, TRUE)]\n\ntr <- phy_tree(ps_pd)\nkeep_tips <- intersect(tr$tip.label, unique(unlist(lapply(inc_by_hab_pd, rownames))))\ntr2 <- ape::keep.tip(tr, keep_tips)\ntr2$node.label <- NULL\nif (!ape::is.rooted(tr2)) tr2 <- phangorn::midpoint(tr2)\n\ntipset <- tr2$tip.label\ninc_by_hab_pd <- lapply(inc_by_hab_pd, function(M) M[rownames(M) %in% tipset, , drop = FALSE])\ninc_by_hab_pd <- inc_by_hab_pd[vapply(inc_by_hab_pd, function(M) nrow(M) > 0 && ncol(M) > 0, TRUE)]\n\nout_PD <- iNEXT3D(data = inc_by_hab_pd, diversity = \"PD\", q = c(0,1,2),\n                  datatype = \"incidence_raw\", nboot = 500, PDtree = tr2, PDtype = \"meanPD\")\n\ntab_s17 <- as.data.frame(out_PD$PDAsyEst) %>% rename(Habitat = Assemblage)\ntab_s17$Habitat <- factor(labs_map[as.character(tab_s17$Habitat)], levels = lvl_order)\n\nwrite.csv(tab_s17, file.path(out_tab_dir, \"Table_S17_iNEXT3D_PD.csv\"), row.names = FALSE)\n```\n:::\n\n\n### 5.3 Abundance-based beta-diversity partitioning (Table S11)\n\nBray–Curtis dissimilarities were partitioned into balanced variation and abundance gradients across taxonomic levels using the `betapart` package. Metrics were calculated from rarefied abundance data.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S11. Bray–Curtis beta-diversity partitioning across taxonomic levels and sites.\n\n|Site |Taxonomic_Level | beta.BRAY.BAL| beta.BRAY.GRA| beta.BRAY|\n|:----|:---------------|-------------:|-------------:|---------:|\n|DOM  |OTU             |        0.9748|        0.0244|    0.9993|\n|DOM  |Genus           |        0.9164|        0.0780|    0.9944|\n|DOM  |Order           |        0.7708|        0.2166|    0.9874|\n|DOM  |Class           |        0.4256|        0.5418|    0.9674|\n|DOM  |Phylum          |        0.2759|        0.6859|    0.9619|\n|NV   |OTU             |        0.9870|        0.0124|    0.9995|\n|NV   |Genus           |        0.9553|        0.0415|    0.9969|\n|NV   |Order           |        0.7846|        0.2059|    0.9905|\n|NV   |Class           |        0.4516|        0.5238|    0.9754|\n|NV   |Phylum          |        0.1470|        0.8046|    0.9516|\n|BEL  |OTU             |        0.9870|        0.0125|    0.9994|\n|BEL  |Genus           |        0.9371|        0.0573|    0.9945|\n|BEL  |Order           |        0.7916|        0.1995|    0.9911|\n|BEL  |Class           |        0.4611|        0.5121|    0.9733|\n|BEL  |Phylum          |        0.0258|        0.9434|    0.9692|\n|MA   |OTU             |        0.9431|        0.0557|    0.9989|\n|MA   |Genus           |        0.9305|        0.0627|    0.9932|\n|MA   |Order           |        0.7966|        0.1911|    0.9877|\n|MA   |Class           |        0.5906|        0.3750|    0.9656|\n|MA   |Phylum          |        0.0000|        0.9504|    0.9505|\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### 5.4 Figure 3: Diversity trajectories\n\n![](figures/Figure_3_iNEXT_rarefaction_trajectories.png)\n\n**Figure 3**: Diversity decline across the elevational gradient. Panel A shows iNEXT3D coverage-based rarefaction/extrapolation curves for TD and PD at $q=0,1,2$ by habitat. Panel B shows per-sample Hill diversity trajectories ($q=1$) for TD and PD, with model-estimated means ± 95% CI for BEL, DOM, and NV (MA excluded). Habitat × site interactions were non-significant for both metrics (TD $F_{4,50}=1.52$, $p=0.21$; PD $F_{4,50}=1.22$, $p=0.31$), supporting parallel diversity erosion across regions.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code used to generate Figure 3 (iNEXT3D coverage curves + per-sample trajectories, main text)\"}\n# =============================================================================\n# Figure 3: iNEXT3D rarefaction curves (TD+PD) + Per-sample diversity trajectories\n# Two-panel figure for main manuscript\n# APPLIES EXACT SAME AESTHETIC AS FIGURE 2 FOR CONSISTENCY\n# =============================================================================\n\nlibrary(ggplot2)\nlibrary(patchwork)\nlibrary(ggrepel)\nlibrary(dplyr)\nlibrary(iNEXT.3D)\nlibrary(phyloseq)\nlibrary(hillR)\nlibrary(ape)\nlibrary(phangorn)\nlibrary(tidyr)\n\n# Need ps_individual, tree_ps, sam, meta from previous sections\nstopifnot(inherits(tree_ps, \"phyloseq\"))\nstopifnot(!is.null(phy_tree(tree_ps, errorIfNULL = FALSE)))\n\n# =============================================================================\n# REUSE FIGURE 2 SHARED AESTHETICS FOR CONSISTENCY\n# =============================================================================\n\n# Colorblind-safe palette (Wong 2011) - EXACT SAME AS FIGURE 2\nsite_colors <- c(\n  BEL = \"#E69F00\",\n  DOM = \"#009E73\",\n  MA  = \"#56B4E9\",\n  NV  = \"#D55E00\"\n)\n\nsite_labels <- c(\n  BEL = \"Belmira\",\n  DOM = \"Las Domínguez\",\n  MA  = \"Matarredonda\",\n  NV  = \"La Nevera\"\n)\n\n# Habitat color palette for Panel A (Dark2 colorblind-safe)\nhabitat_colors <- c(\n  \"Forest\"    = \"#1b9e77\",\n  \"Subpáramo\" = \"#d95f02\",\n  \"Páramo\"    = \"#7570b3\"\n)\n\n# EXACT SAME BASE THEME AS FIGURE 2\nbase_theme <- theme_classic(base_size = 11) +\n  theme(\n    axis.title      = element_text(size = 9),\n    axis.text       = element_text(size = 7, color = \"black\"),\n    legend.title    = element_text(size = 5, face = \"bold\"),\n    legend.text     = element_text(size = 4.5),\n    legend.key.size = unit(0.6, \"lines\"),\n    legend.position = \"right\",\n    plot.tag        = element_text(size = 13, face = \"bold\"),\n    strip.background = element_blank()\n  )\n\n# Habitat labeling consistent with FIGURE 2\nlabs_map  <- c(forest = \"Forest\", subparamo = \"Subpáramo\", paramo = \"Páramo\")\nlvl_order <- c(\"Forest\", \"Subpáramo\", \"Páramo\")\n\n# =========================================\n# PANEL A: iNEXT3D RAREFACTION CURVES (TD + PD combined)\n# =========================================\n\n# NOTE: out_TD and out_PD are pre-computed in Section 5.2 above.\n# Extract coverage-based rarefaction curves for Panel A directly from those objects.\ntd_data <- out_TD$TDiNextEst$coverage_based\npd_data <- out_PD$PDiNextEst$coverage_based\n\n# Relabel habitat names in both datasets (KEEP ALL q VALUES for Panel A)\nrelabel_data <- function(df, metric_name) {\n  if (!is.null(df) && is.data.frame(df)) {\n    assemblage_col <- dplyr::case_when(\n      \"Assemblage\" %in% names(df) ~ \"Assemblage\",\n      \"assemblage\" %in% names(df) ~ \"assemblage\",\n      TRUE ~ NA_character_\n    )\n\n    if (is.na(assemblage_col)) {\n      stop(\"No assemblage column found in iNEXT3D output (expected 'Assemblage' or 'assemblage').\")\n    }\n\n    assemblage_raw <- as.character(df[[assemblage_col]])\n    habitat_mapped <- unname(labs_map[assemblage_raw])\n    habitat_mapped[is.na(habitat_mapped)] <- assemblage_raw[is.na(habitat_mapped)]\n\n    # iNEXT3D uses qTD for TD and qPD for PD; select whichever exists.\n    diversity_col <- dplyr::case_when(\n      \"qTD\" %in% names(df) ~ \"qTD\",\n      \"qPD\" %in% names(df) ~ \"qPD\",\n      \"qD\"  %in% names(df) ~ \"qD\",\n      TRUE ~ NA_character_\n    )\n\n    ci_low_col <- dplyr::case_when(\n      \"qTD.LCL\" %in% names(df) ~ \"qTD.LCL\",\n      \"qPD.LCL\" %in% names(df) ~ \"qPD.LCL\",\n      \"qD.LCL\"  %in% names(df) ~ \"qD.LCL\",\n      \"q.low\"   %in% names(df) ~ \"q.low\",\n      TRUE ~ NA_character_\n    )\n\n    ci_up_col <- dplyr::case_when(\n      \"qTD.UCL\" %in% names(df) ~ \"qTD.UCL\",\n      \"qPD.UCL\" %in% names(df) ~ \"qPD.UCL\",\n      \"qD.UCL\"  %in% names(df) ~ \"qD.UCL\",\n      \"q.up\"    %in% names(df) ~ \"q.up\",\n      TRUE ~ NA_character_\n    )\n\n    if (is.na(diversity_col)) {\n      stop(\"No diversity column found in iNEXT3D output (expected one of: qTD, qPD, qD).\")\n    }\n\n    # Keep Order.q column for faceting by q values in Panel A\n    df <- df %>%\n      dplyr::mutate(\n        habitat = factor(habitat_mapped, levels = lvl_order),\n        metric = metric_name\n      ) %>%\n      dplyr::rename(coverage = SC) %>%\n      dplyr::rename(diversity = dplyr::all_of(diversity_col))\n\n    # Standardize CI columns for ribbons; allow missing CI without crashing.\n    if (!is.na(ci_low_col) && !is.na(ci_up_col)) {\n      df <- df %>%\n        dplyr::rename(ci_low = dplyr::all_of(ci_low_col),\n                      ci_up  = dplyr::all_of(ci_up_col))\n    } else {\n      df$ci_low <- NA_real_\n      df$ci_up  <- NA_real_\n    }\n  }\n  df\n}\n\ntd_data <- relabel_data(td_data, \"TD\")\npd_data <- relabel_data(pd_data, \"PD\")\n\n# Combine for faceted plotting\ncombined_data <- dplyr::bind_rows(td_data, pd_data) %>%\n  dplyr::mutate(\n    habitat = factor(habitat, levels = lvl_order),\n    q_label = paste0(\"q=\", Order.q),\n    Method_plot = dplyr::case_when(\n      grepl(\"rare\", Method, ignore.case = TRUE) ~ \"Rarefaction\",\n      grepl(\"extra\", Method, ignore.case = TRUE) ~ \"Extrapolation\",\n      grepl(\"obs\", Method, ignore.case = TRUE) ~ \"Observed\",\n      TRUE ~ as.character(Method)\n    )\n  )\n\n# Use true observed points when present; fallback to max rarefaction coverage otherwise.\nif (\"Observed\" %in% unique(as.character(combined_data$Method_plot))) {\n  observed_pts <- combined_data %>% dplyr::filter(Method_plot == \"Observed\")\n} else {\n  observed_pts <- combined_data %>%\n    dplyr::filter(Method_plot == \"Rarefaction\") %>%\n    dplyr::group_by(habitat, metric, Order.q) %>%\n    dplyr::slice_max(coverage, n = 1) %>%\n    dplyr::ungroup()\n}\n\n# Draw lines only for rarefaction/extrapolation segments.\nline_data <- combined_data %>% dplyr::filter(Method_plot != \"Observed\")\n\n# Build Panel A as two stacked sub-panels so TD and PD can each use free_y independently.\nbase_iNEXT_plot <- function(data, obs_pts, lines, y_lab, tag_label = NULL) {\n  ggplot(data, aes(x = coverage, y = diversity, color = habitat)) +\n    geom_ribbon(\n      aes(ymin = ci_low, ymax = ci_up, fill = habitat),\n      alpha = 0.15,\n      color = NA,\n      show.legend = FALSE\n    ) +\n    geom_line(\n      data = lines,\n      aes(linetype = Method_plot, group = interaction(habitat, Method_plot, q_label)),\n      linewidth = 0.85,\n      alpha = 0.85\n    ) +\n    geom_point(\n      data = obs_pts,\n      size = 1.8,\n      alpha = 0.9\n    ) +\n    facet_wrap(~ q_label, nrow = 1, scales = \"free_y\") +\n    scale_color_manual(values = habitat_colors, name = NULL) +\n    scale_fill_manual(values = habitat_colors, guide = \"none\") +\n    scale_linetype_manual(\n      values = c(\"Rarefaction\" = \"solid\", \"Extrapolation\" = \"dashed\"),\n      name = NULL\n    ) +\n    labs(x = \"Coverage\", y = y_lab, tag = tag_label) +\n    base_theme +\n    theme(\n      axis.title = element_text(size = 9),\n      strip.text = element_text(size = 8)\n    )\n}\n\ntd_combined <- combined_data %>% dplyr::filter(metric == \"TD\")\npd_combined <- combined_data %>% dplyr::filter(metric == \"PD\")\n\ntd_obs <- observed_pts %>% dplyr::filter(metric == \"TD\")\npd_obs <- observed_pts %>% dplyr::filter(metric == \"PD\")\n\ntd_lines <- line_data %>% dplyr::filter(metric == \"TD\")\npd_lines <- line_data %>% dplyr::filter(metric == \"PD\")\n\npanel_A_TD <- base_iNEXT_plot(\n  td_combined,\n  td_obs,\n  td_lines,\n  y_lab = \"Taxonomic diversity\",\n  tag_label = \"A\"\n) +\n  theme(legend.position = \"none\")\n\npanel_A_PD <- base_iNEXT_plot(\n  pd_combined,\n  pd_obs,\n  pd_lines,\n  y_lab = \"Phylogenetic diversity (meanPD)\",\n  tag_label = NULL\n) +\n  guides(\n    linetype = guide_legend(order = 1, nrow = 1),\n    color = guide_legend(order = 2, nrow = 1)\n  ) +\n  theme(\n    legend.position = \"bottom\",\n    legend.direction = \"horizontal\",\n    legend.box = \"horizontal\",\n    legend.justification = \"center\",\n    legend.title = element_blank(),\n    legend.text = element_text(size = 5),\n    legend.key.width = unit(1.2, \"lines\"),\n    legend.spacing.x = unit(0.6, \"lines\"),\n    legend.margin = margin(t = 1, r = 0, b = 0, l = 0)\n  )\n\npanel_A <- panel_A_TD / panel_A_PD\n\n# =========================================\n# PANEL B: PER-SAMPLE DIVERSITY TRAJECTORIES\n# =========================================\n\n# Reuse per-sample data and fitted models already computed in TD/PD section.\nstopifnot(exists(\"div_long\"))\nstopifnot(exists(\"m_td_factor\") || exists(\"m_td\"))\nstopifnot(exists(\"m_pd_factor\") || exists(\"m_pd\"))\n\nm_td_reuse <- if (exists(\"m_td_factor\")) m_td_factor else m_td\nm_pd_reuse <- if (exists(\"m_pd_factor\")) m_pd_factor else m_pd\n\nlibrary(emmeans)\n\n# For lm(log(y) ~ ...), manually back-transform from log scale.\nemm_td_plot <- as.data.frame(\n  summary(emmeans(m_td_reuse, ~ habitat | site), infer = c(TRUE, TRUE))\n) %>%\n  dplyr::mutate(\n    response = exp(emmean),\n    lower.CL = exp(lower.CL),\n    upper.CL = exp(upper.CL),\n    metric = \"TD (q=1)\",\n    habitat = factor(\n      as.character(habitat),\n      levels = c(\"forest\", \"subparamo\", \"paramo\"),\n      labels = c(\"Forest\", \"Subpáramo\", \"Páramo\"),\n      ordered = TRUE\n    ),\n    site = factor(as.character(site), levels = c(\"BEL\", \"DOM\", \"MA\", \"NV\"))\n  )\n\nemm_pd_plot <- as.data.frame(\n  summary(emmeans(m_pd_reuse, ~ habitat | site), infer = c(TRUE, TRUE))\n) %>%\n  dplyr::mutate(\n    response = exp(emmean),\n    lower.CL = exp(lower.CL),\n    upper.CL = exp(upper.CL),\n    metric = \"PD (q=1)\",\n    habitat = factor(\n      as.character(habitat),\n      levels = c(\"forest\", \"subparamo\", \"paramo\"),\n      labels = c(\"Forest\", \"Subpáramo\", \"Páramo\"),\n      ordered = TRUE\n    ),\n    site = factor(as.character(site), levels = c(\"BEL\", \"DOM\", \"MA\", \"NV\"))\n  )\n\nemm_plot <- dplyr::bind_rows(emm_td_plot, emm_pd_plot)\n\n# Prepare data for Panel B (EXCLUDE MA due to incomplete gradient)\ndiv_long$habitat_lab <- factor(\n  div_long$habitat,\n  levels = c(\"forest\", \"subparamo\", \"paramo\"),\n  labels = c(\"Forest\", \"Subpáramo\", \"Páramo\")\n)\ndiv_long$site_fac <- factor(div_long$site, levels = c(\"BEL\", \"DOM\", \"MA\", \"NV\"))\n\n# Filter to exclude MA (incomplete gradient — no forest baseline)\ndiv_long_plot <- div_long %>% dplyr::filter(site != \"MA\")\nemm_plot_plot <- emm_plot %>% dplyr::filter(site != \"MA\")\n\nemm_plot_plot$habitat_lab <- emm_plot_plot$habitat\nemm_plot_plot$site_fac <- emm_plot_plot$site\n\nmodel_dodge <- position_dodge(width = 0.30)\n\n# Panel B: Per-sample trajectories - FIGURE 2 AESTHETIC (MA excluded)\npanel_B <- ggplot(div_long_plot, aes(x = habitat_lab, y = estimate, color = site_fac)) +\n  geom_point(\n    aes(group = site_fac),\n    position = position_jitterdodge(jitter.width = 0.08, dodge.width = 0.30),\n    alpha = 0.45,\n    size = 1.2\n  ) +\n  geom_errorbar(\n    data = emm_plot_plot,\n    aes(x = habitat_lab, ymin = lower.CL, ymax = upper.CL, color = site_fac, group = site_fac),\n    width = 0.10,\n    linewidth = 0.5,\n    position = model_dodge,\n    inherit.aes = FALSE\n  ) +\n  geom_line(\n    data = emm_plot_plot,\n    aes(x = habitat_lab, y = response, color = site_fac, group = site_fac),\n    linewidth = 0.9,\n    position = model_dodge,\n    inherit.aes = FALSE\n  ) +\n  geom_point(\n    data = emm_plot_plot,\n    aes(x = habitat_lab, y = response, color = site_fac, group = site_fac),\n    size = 2.2,\n    position = model_dodge,\n    inherit.aes = FALSE\n  ) +\n  facet_wrap(~metric, scales = \"free_y\", nrow = 1) +\n  scale_color_manual(values = site_colors, labels = site_labels, name = \"Site\") +\n  labs(\n    x = \"Habitat\",\n    y = \"Per-sample Hill diversity\",\n    tag = \"B\"\n  ) +\n  base_theme +\n  theme(\n    legend.position = \"right\",\n    axis.title = element_text(size = 9),\n    axis.text.x = element_text(angle = 15, hjust = 1, vjust = 1),\n    strip.text = element_text(size = 8)\n  ) +\n  guides(color = guide_legend(override.aes = list(size = 2, linewidth = 0.8)))\n\n# =============================================================================\n# COMBINE PANELS WITH PATCHWORK - EXACT LAYOUT AS FIGURE 2\n# =============================================================================\n\nfig3 <- ((panel_A_TD / panel_A_PD) | panel_B) +\n  plot_layout(widths = c(1.1, 1), guides = \"keep\")\n\nggsave(\n  filename = file.path(out_fig_dir, \"Figure_3_iNEXT_rarefaction_trajectories.png\"),\n  plot = fig3, width = 17.4, height = 6.8, units = \"cm\", dpi = 900, bg = \"white\"\n)\n```\n:::\n\n\n## Section 6: Lineage-specific responses\n\n### 6.1 Beta regression models (Tables S12–S14)\n\nTo quantify elevational trends in the relative abundance of dominant fungal lineages, we fitted beta-regression models to order-level relative read abundances. Models were fitted separately for each order using a logit link, with elevation as a continuous predictor and site included as a fixed effect. Relative abundances were calculated as proportions of total reads per sample and transformed using a Smithson–Verkuilen adjustment.\n\nWe focus on helotiales and sebacinales, the two most abundant orders, which also showed the only significant elevation responses. For both orders, fitted relationships and raw data are shown in Figure 4 (Panels A-B), while full model summaries are provided in Tables S12 and S13. Elevation effects for the eight most abundant orders are summarized in Table S14.\n\nModel diagnostics were examined to assess fit and identify potential violations of distributional assumptions. Diagnostic plots include Pearson residuals versus fitted values and elevation, quantile residual Q–Q plots, and leverage values (Figures S5–S6).\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S12. Beta regression summary for Helotiales (mean model coefficients and precision (phi)).\n\n|Model      |Term        | Estimate|     SE|       z|      p|\n|:----------|:-----------|--------:|------:|-------:|------:|\n|helotiales |(Intercept) |  -3.2040| 1.2559| -2.5512| 0.0107|\n|helotiales |elevation   |   0.0010| 0.0004|  2.3959| 0.0166|\n|helotiales |siteDOM     |  -0.7291| 0.3651| -1.9969| 0.0458|\n|helotiales |siteMA      |   0.0050| 0.3871|  0.0130| 0.9896|\n|helotiales |siteNV      |  -0.8864| 0.3346| -2.6494| 0.0081|\n|helotiales |(phi) (phi) |   6.2698| 1.0711|  5.8534| 0.0000|\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S13. Beta regression summary for Sebacinales (mean model coefficients and precision (phi)).\n\n|Model       |Term        | Estimate|     SE|       z|      p|\n|:-----------|:-----------|--------:|------:|-------:|------:|\n|sebacinales |(Intercept) |   0.4169| 1.3941|  0.2990| 0.7649|\n|sebacinales |elevation   |  -0.0010| 0.0005| -2.1320| 0.0330|\n|sebacinales |siteDOM     |   0.7196| 0.4162|  1.7289| 0.0838|\n|sebacinales |siteMA      |   0.3029| 0.4603|  0.6580| 0.5105|\n|sebacinales |siteNV      |   0.9779| 0.3714|  2.6333| 0.0085|\n|sebacinales |(phi) (phi) |  10.1810| 2.0241|  5.0298| 0.0000|\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S14. Elevation effects from beta regression models for the dominant orders (mean submodel), with pseudo-R².\n\n|order           |term      | estimate|    se|       z| p_value| pseudo_R2|\n|:---------------|:---------|--------:|-----:|-------:|-------:|---------:|\n|helotiales      |elevation |    1e-03| 4e-04|  2.3959|  0.0166|    0.2133|\n|sebacinales     |elevation |   -1e-03| 5e-04| -2.1320|  0.0330|    0.2261|\n|chaetothyriales |elevation |    1e-04| 4e-04|  0.2327|  0.8160|    0.0239|\n|sclerococcales  |elevation |    7e-04| 5e-04|  1.3758|  0.1689|    0.1330|\n|agaricales      |elevation |   -7e-04| 4e-04| -1.7597|  0.0785|    0.0929|\n|pleosporales    |elevation |   -4e-04| 4e-04| -1.0668|  0.2861|    0.1528|\n|hypocreales     |elevation |   -2e-04| 3e-04| -0.7300|  0.4654|    0.2397|\n|leotiales       |elevation |   -2e-04| 3e-04| -0.6812|  0.4957|    0.2964|\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n![](figures/Fig_S5_betareg_diagnostics_helotiales.png)\n\n**Figure S5**: Diagnostic plots for the beta-regression model of Helotiales. *Code: see \"Beta-regression models\" below.*\n\n------------------------------------------------------------------------\n\n![](figures/Fig_S6_betareg_diagnostics_sebacinales.png)\n\n**Figure S6**: Diagnostic plots for the beta-regression model of Sebacinales. *Code: see \"Beta-regression models\" below.*\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Beta-regression models (executed on remote server)\"}\n# This code fits beta-regression models for dominant fungal orders,\n# generates Tables S12–S14, and exports Figures S5–S6 as PNG files.\n\nlibrary(phyloseq)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(betareg)\nlibrary(patchwork)\n\n\nout_fig_dir <- \"figures\"\nout_tab_dir <- \"tables\"\n\nset.seed(1)\n\n## ---- Helper: build beta-regression dataframe for an Order ----\nmake_beta_df_from_order <- function(ps, order_name) {\n\n  otu <- as(otu_table(ps), \"matrix\")\n  if (!taxa_are_rows(ps)) otu <- t(otu)  # taxa x samples\n\n  sd <- as.data.frame(sample_data(ps))\n  sd <- sd[colnames(otu), , drop = FALSE]  # force alignment\n\n  tax <- as.data.frame(tax_table(ps), stringsAsFactors = FALSE)\n  stopifnot(\"Order\" %in% names(tax))\n\n  order_vec <- tolower(as.character(tax$Order))\n  order_vec[is.na(order_vec)] <- \"\"\n\n  otu_ids <- rownames(tax)[grepl(tolower(order_name), order_vec, fixed = TRUE)]\n  if (length(otu_ids) == 0) stop(paste(\"No OTUs found for\", order_name))\n\n  counts <- colSums(otu[otu_ids, , drop = FALSE])\n  total  <- colSums(otu)\n\n  samps <- colnames(otu)\n\n  df <- data.frame(\n    sample    = samps,\n    count     = as.numeric(counts),\n    total     = as.numeric(total),\n    prop_raw  = ifelse(total > 0, counts / total, NA_real_),\n    site      = sd[, \"site\", drop = TRUE],\n    elevation = sd[, \"elevation\", drop = TRUE],\n    stringsAsFactors = FALSE\n  )\n\n  # Smithson–Verkuilen adjustment to (0,1)\n  n <- nrow(df)\n  df$Proportion <- (df$prop_raw * (n - 1) + 0.5) / n\n\n  df$site <- factor(df$site)\n  df$elevation <- as.numeric(df$elevation)\n\n  df\n}\n\n## ---- Helper: tidy coefficient table for Tables S12/S13 ----\ntidy_betareg_mean <- function(mod, model_name) {\n  sm <- summary(mod)\n  co <- as.data.frame(sm$coefficients$mean)\n  co$Term <- rownames(co)\n  rownames(co) <- NULL\n  names(co) <- c(\"Estimate\",\"SE\",\"z\",\"p\",\"Term\")\n\n  # move Term first + add model label\n  co <- co %>%\n    select(Term, Estimate, SE, z, p) %>%\n    mutate(Model = model_name, .before = 1)\n\n  # also add phi (precision) row, for completeness\n  phi <- as.data.frame(sm$coefficients$precision)\n  phi$Term <- rownames(phi); rownames(phi) <- NULL\n  names(phi) <- c(\"Estimate\",\"SE\",\"z\",\"p\",\"Term\")\n  phi <- phi %>%\n    select(Term, Estimate, SE, z, p) %>%\n    mutate(Model = model_name, .before = 1) %>%\n    mutate(Term = paste0(Term, \" (phi)\"))\n\n  bind_rows(co, phi)\n}\n\n## ---- Helper: elevation-only summary across orders for Table S14 ----\nextract_elev <- function(mod, order_name) {\n  sm <- summary(mod)\n  co <- sm$coefficients$mean\n  if (!(\"elevation\" %in% rownames(co))) return(NULL)\n  data.frame(\n    order = order_name,\n    term  = \"elevation\",\n    estimate  = co[\"elevation\",\"Estimate\"],\n    se        = co[\"elevation\",\"Std. Error\"],\n    z         = co[\"elevation\",\"z value\"],\n    p_value   = co[\"elevation\",\"Pr(>|z|)\"],\n    pseudo_R2 = sm$pseudo.r.squared,\n    stringsAsFactors = FALSE\n  )\n}\n\n## ---- 1) Fit models ----\norders_target <- c(\n  \"helotiales\",\n  \"sebacinales\",\n  \"chaetothyriales\",\n  \"sclerococcales\",\n  \"agaricales\",\n  \"pleosporales\",\n  \"hypocreales\",\n  \"leotiales\"\n)\n\ndf_list  <- setNames(vector(\"list\", length(orders_target)), orders_target)\nmod_list <- setNames(vector(\"list\", length(orders_target)), orders_target)\n\nfor (ord in orders_target) {\n  message(\"Building DF + fitting: \", ord)\n  df_list[[ord]]  <- make_beta_df_from_order(ps, ord)\n  mod_list[[ord]] <- betareg(Proportion ~ elevation + site, data = df_list[[ord]])\n}\n\n## ---- 2) Tables S12/S13: helotiales + sebacinales full model tables ----\ntab_s12_helot <- tidy_betareg_mean(mod_list[[\"helotiales\"]], \"helotiales\")\ntab_s13_seba  <- tidy_betareg_mean(mod_list[[\"sebacinales\"]], \"sebacinales\")\n\nwrite.csv(tab_s12_helot,\n          file.path(out_tab_dir, \"Table_S12_betareg_helotiales.csv\"),\n          row.names = FALSE)\nwrite.csv(tab_s13_seba,\n          file.path(out_tab_dir, \"Table_S13_betareg_sebacinales.csv\"),\n          row.names = FALSE)\n\n## ---- 3) Table S14: elevation effects across orders ----\ntab_s14 <- bind_rows(lapply(names(mod_list), \\(ord) extract_elev(mod_list[[ord]], ord)))\nwrite.csv(tab_s14,\n          file.path(out_tab_dir, \"Table_S14_betareg_other_orders.csv\"),\n          row.names = FALSE)\n\n\n\n## ---- 4) Beta regression plots for Helotiales + Sebacinales ----\n\n# helper\ninv_logit <- function(x) 1 / (1 + exp(-x))\n\nplot_betareg_with_raw <- function(model, data, label_prefix = \"helotiales\") {\n\n  # Ensure required columns exist\n  stopifnot(all(c(\"site\",\"elevation\",\"prop_raw\") %in% names(data)))\n\n  data <- data[complete.cases(data[, c(\"site\",\"elevation\",\"prop_raw\")]), , drop = FALSE]\n\n  # Align site factor levels to model\n  if (!is.null(model$xlevels$mean$site)) {\n    data$site <- factor(as.character(data$site), levels = model$xlevels$mean$site)\n  } else {\n    data$site <- factor(data$site)\n  }\n\n  # Drop any rows that became NA due to level mismatch\n  data <- data[!is.na(data$site), , drop = FALSE]\n\n  one_level_site <- (nlevels(droplevels(data$site)) < 2)\n\n  # Build prediction grid by site across observed elevation range\n  newdat <- data %>%\n    dplyr::select(site, elevation) %>%\n    dplyr::distinct() %>%\n    dplyr::group_by(site) %>%\n    dplyr::summarize(\n      elev_min = min(elevation, na.rm = TRUE),\n      elev_max = max(elevation, na.rm = TRUE),\n      .groups = \"drop\"\n    ) %>%\n    dplyr::rowwise() %>%\n    dplyr::mutate(elevation = list(seq(elev_min, elev_max, length.out = 100))) %>%\n    tidyr::unnest(elevation) %>%\n    dplyr::select(site, elevation) %>%\n    dplyr::ungroup()\n\n  # Re-apply model levels to newdat site\n  if (!is.null(model$xlevels$mean$site)) {\n    newdat$site <- factor(as.character(newdat$site), levels = model$xlevels$mean$site)\n  } else {\n    newdat$site <- factor(newdat$site)\n  }\n\n  # If we only have 1 site level, disable contrasts to prevent the error\n  if (one_level_site) {\n    contrasts(newdat$site) <- NULL\n  }\n\n  # Design matrix for mean submodel\n  mean_terms <- stats::delete.response(stats::terms(model, model = \"mean\"))\n  X <- model.matrix(mean_terms, newdat)\n\n  beta <- coef(model, model = \"mean\")\n  V <- try(vcov(model, model = \"mean\"), silent = TRUE)\n  if (inherits(V, \"try-error\")) V <- vcov(model)\n\n  eta    <- as.vector(X %*% beta)\n  se_eta <- sqrt(rowSums((X %*% V) * X))\n\n  newdat$fit <- inv_logit(eta)\n  newdat$lwr <- inv_logit(eta - 1.96 * se_eta)\n  newdat$upr <- inv_logit(eta + 1.96 * se_eta)\n\n  # Plot\n  ggplot() +\n    geom_point(\n      data = data,\n      aes(x = elevation, y = prop_raw, colour = site),\n      size = 2, alpha = 0.7\n    ) +\n    geom_ribbon(\n      data = newdat,\n      aes(x = elevation, ymin = lwr, ymax = upr, fill = site, group = site),\n      alpha = 0.15, colour = NA\n    ) +\n    geom_line(\n      data = newdat,\n      aes(x = elevation, y = fit, colour = site, group = site),\n      linewidth = 0.8\n    ) +\n    scale_y_continuous(\"Relative abundance (raw proportion)\", limits = c(0, 1)) +\n    scale_x_continuous(\"Elevation (m)\") +\n    ggtitle(label_prefix) +\n    theme_bw(base_size = 10) +\n    theme(\n      plot.title = element_text(face = \"bold\", size = 12, hjust = 0),\n      legend.position = \"bottom\"\n    )\n}\n\n# Build plots\np_helot <- plot_betareg_with_raw(mod_list[[\"helotiales\"]], df_list[[\"helotiales\"]], \"A) helotiales\")\np_seba  <- plot_betareg_with_raw(mod_list[[\"sebacinales\"]], df_list[[\"sebacinales\"]], \"B) sebacinales\")\n\n# Combine and save\npanel_beta <- (p_helot | p_seba) + patchwork::plot_layout(guides = \"collect\")\n\n# Note: standalone betareg panel superseded by Figure_4_betareg_GLLVM_combined.png\n\n\n## ---- 5) Diagnostic plots for Helotiales + Sebacinales ----\n\nplot_betareg_diagnostics <- function(model, data, label_prefix = \"Helotiales\") {\n\n  # Ensure alignment (betareg expects the same row order it was fitted with)\n  data <- data[complete.cases(data[, c(\"elevation\",\"site\",\"Proportion\")]), , drop = FALSE]\n\n  # residuals & fitted\n  res_pear  <- residuals(model, type = \"pearson\")\n  res_quant <- residuals(model, type = \"quantile\")   # approx N(0,1)\n  fit       <- fitted(model)\n  hatv      <- hatvalues(model)\n\n  diagdf <- data.frame(\n    fitted    = fit,\n    res_pear  = res_pear,\n    res_quant = res_quant,\n    elevation = data$elevation,\n    site      = as.factor(data$site),\n    hat       = hatv,\n    idx       = seq_len(nrow(data))\n  )\n\n  # (1) Residuals vs Fitted\n  p1 <- ggplot(diagdf, aes(fitted, res_pear)) +\n    geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey40\") +\n    geom_point(alpha = 0.7, size = 1.8) +\n    geom_smooth(method = \"loess\", se = FALSE, linewidth = 0.5) +\n    labs(x = \"Fitted values\", y = \"Pearson residuals\",\n         title = paste(label_prefix, \"– Residuals vs Fitted\")) +\n    theme_bw(base_size = 9)\n\n  # (2) Residuals vs Elevation\n  p2 <- ggplot(diagdf, aes(elevation, res_pear)) +\n    geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey40\") +\n    geom_point(alpha = 0.7, size = 1.8) +\n    geom_smooth(method = \"loess\", se = FALSE, linewidth = 0.5) +\n    labs(x = \"Elevation (m)\", y = \"Pearson residuals\",\n         title = paste(label_prefix, \"– Residuals vs Elevation\")) +\n    theme_bw(base_size = 9)\n\n  # (3) Q–Q plot of quantile residuals\n  p3 <- ggplot(diagdf, aes(sample = res_quant)) +\n    stat_qq(size = 1.4, alpha = 0.8) +\n    stat_qq_line() +\n    labs(title = paste(label_prefix, \"– Q–Q Plot (quantile residuals)\"),\n         x = \"Theoretical quantiles\", y = \"Sample quantiles\") +\n    theme_bw(base_size = 9)\n\n  # (4) Leverage\n  hat_thr <- 2 * mean(diagdf$hat, na.rm = TRUE)\n  p4 <- ggplot(diagdf, aes(idx, hat)) +\n    geom_point(alpha = 0.85, size = 1.8) +\n    geom_hline(yintercept = hat_thr, color = \"red\", linetype = \"dashed\") +\n    labs(x = \"Observation index\", y = \"Leverage (hat values)\",\n         title = paste(label_prefix, \"– Leverage\")) +\n    theme_bw(base_size = 9)\n\n  (p1 | p2) / (p3 | p4) +\n    patchwork::plot_annotation(title = paste(label_prefix, \"model diagnostics\")) &\n    theme(plot.title = element_text(face = \"bold\", size = 10, hjust = 0))\n}\n\n# Use your existing objects from Steps 1–3\ndiag_helot <- plot_betareg_diagnostics(mod_list[[\"helotiales\"]],  df_list[[\"helotiales\"]],  \"Helotiales\")\ndiag_seba  <- plot_betareg_diagnostics(mod_list[[\"sebacinales\"]], df_list[[\"sebacinales\"]], \"Sebacinales\")\n\nggsave(\n  filename = file.path(out_fig_dir, \"Fig_S5_betareg_diagnostics_helotiales.png\"),\n  plot = diag_helot, width = 8.5, height = 6.5, dpi = 900\n)\n\nggsave(\n  filename = file.path(out_fig_dir, \"Fig_S6_betareg_diagnostics_sebacinales.png\"),\n  plot = diag_seba, width = 8.5, height = 6.5, dpi = 900\n)\n```\n:::\n\n\n### 6.2 Figure 4: Elevational trends and OTU habitat responses {.page-break-before}\n\nThree-panel composite figure combining order-level elevational trends (beta-regression for the two most abundant and responsive orders) with OTU-level habitat associations from the GLLVM model. Panel A and B show fitted beta-regression relationships for *Helotiales* and *Sebacinales* across sampling sites with raw data overlaid. Panel C presents the genus-level GLLVM heatmap showing weighted habitat contrast effects (páramo and subpáramo relative to forest) for the most responsive taxa.\n\n![](figures/Figure_4_betareg_GLLVM_combined.png)\n\n**Figure 4**: Elevational trends and OTU-level habitat responses. Panel A: Helotiales relative abundance versus elevation (approximately +10.1% per 100 m, $p=0.016$). Panel B: Sebacinales relative abundance versus elevation (approximately -10.0% per 100 m, $p=0.033$). Panel C: GLLVM heatmap of genus-level coefficients for páramo vs forest and subpáramo vs forest contrasts.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code used to generate Figure 4 (three-panel composite of beta-regression + GLLVM, using pre-fitted models)\"}\n# =============================================================================\n# FIGURE 4: Beta-regression elevation trends + GLLVM habitat response heatmap\n# Three-panel figure combining order-level and OTU-level analyses\n#\n# ASSUMED OBJECTS (already in workspace from prior sections):\n#   - mod_list:   fitted beta-regression models (helotiales, sebacinales, etc.)\n#   - df_list:    data frames used to fit models (contains site, elevation, prop_raw)\n#   Both created in the \"Beta-regression models\" section (executed on remote server)\n#\n# SHARED AESTHETICS: \n#   Reuses site colors and base theme from Figure 2 & 3 for visual consistency\n# =============================================================================\n\nlibrary(ggplot2)\nlibrary(patchwork)\nlibrary(dplyr)\nlibrary(tidyr)\n\n# ===== STEP 1: Define shared aesthetics (from Figure 2 & 3) =====\n# Colorblind-safe palette (Wong 2011) - EXACT SAME AS FIGURE 2 & 3\nsite_colors <- c(\n  BEL = \"#E69F00\",\n  DOM = \"#009E73\",\n  MA  = \"#56B4E9\",\n  NV  = \"#D55E00\"\n)\n\nsite_labels <- c(\n  BEL = \"Belmira\",\n  DOM = \"Las Domínguez\",\n  MA  = \"Matarredonda\",\n  NV  = \"La Nevera\"\n)\n\n# EXACT SAME BASE THEME AS FIGURE 2 & 3\nbase_theme <- theme_classic(base_size = 11) +\n  theme(\n    axis.title      = element_text(size = 9),\n    axis.text       = element_text(size = 7, color = \"black\"),\n    legend.title    = element_text(size = 7, face = \"bold\"),\n    legend.text     = element_text(size = 7),\n    legend.key.size = unit(0.8, \"lines\"),\n    legend.position = \"right\",\n    plot.tag        = element_text(size = 13, face = \"bold\"),\n    strip.background = element_blank()\n  )\n\n# ===== STEP 2: Helper functions =====\ninv_logit <- function(x) 1 / (1 + exp(-x))\n\n# Modified beta-regression plot function with Figure 2/3 shared aesthetics\nplot_betareg_fig4 <- function(\n  model,\n  data,\n  label_prefix = \"helotiales\",\n  y_limits = c(0, 1),\n  x_limits = NULL,\n  x_label = \"Elevation (m)\",\n  effect_label = NULL\n) {\n  \n  # Ensure required columns exist\n  stopifnot(all(c(\"site\",\"elevation\",\"prop_raw\") %in% names(data)))\n  \n  data <- data[complete.cases(data[, c(\"site\",\"elevation\",\"prop_raw\")]), , drop = FALSE]\n  \n  # Align site factor levels to model\n  if (!is.null(model$xlevels$mean$site)) {\n    data$site <- factor(as.character(data$site), levels = model$xlevels$mean$site)\n  } else {\n    data$site <- factor(data$site)\n  }\n  \n  data <- data[!is.na(data$site), , drop = FALSE]\n  one_level_site <- (nlevels(droplevels(data$site)) < 2)\n  \n  # Build prediction grid by site across observed elevation range\n  newdat <- data %>%\n    dplyr::select(site, elevation) %>%\n    dplyr::distinct() %>%\n    dplyr::group_by(site) %>%\n    dplyr::summarize(\n      elev_min = min(elevation, na.rm = TRUE),\n      elev_max = max(elevation, na.rm = TRUE),\n      .groups = \"drop\"\n    ) %>%\n    dplyr::rowwise() %>%\n    dplyr::mutate(elevation = list(seq(elev_min, elev_max, length.out = 100))) %>%\n    tidyr::unnest(elevation) %>%\n    dplyr::select(site, elevation) %>%\n    dplyr::ungroup()\n  \n  # Re-apply model levels to newdat site\n  if (!is.null(model$xlevels$mean$site)) {\n    newdat$site <- factor(as.character(newdat$site), levels = model$xlevels$mean$site)\n  } else {\n    newdat$site <- factor(newdat$site)\n  }\n  \n  if (one_level_site) {\n    contrasts(newdat$site) <- NULL\n  }\n  \n  # Design matrix for mean submodel\n  mean_terms <- stats::delete.response(stats::terms(model, model = \"mean\"))\n  X <- model.matrix(mean_terms, newdat)\n  \n  beta <- coef(model, model = \"mean\")\n  V <- try(vcov(model, model = \"mean\"), silent = TRUE)\n  if (inherits(V, \"try-error\")) V <- vcov(model)\n  \n  eta    <- as.vector(X %*% beta)\n  se_eta <- sqrt(rowSums((X %*% V) * X))\n  \n  newdat$fit <- inv_logit(eta)\n  newdat$lwr <- inv_logit(eta - 1.96 * se_eta)\n  newdat$upr <- inv_logit(eta + 1.96 * se_eta)\n  \n  # Convert site to factor for consistent color mapping\n  newdat$site <- factor(newdat$site, levels = names(site_colors))\n  data$site <- factor(data$site, levels = names(site_colors))\n  \n  # Plot with shared aesthetics (Figure 2 & 3 style)\n  ggplot() +\n    geom_point(\n      data = data,\n      aes(x = elevation, y = prop_raw, colour = site),\n      size = 1.8, alpha = 0.7\n    ) +\n    geom_ribbon(\n      data = newdat,\n      aes(x = elevation, ymin = lwr, ymax = upr, fill = site, group = site),\n      alpha = 0.15, colour = NA\n    ) +\n    geom_line(\n      data = newdat,\n      aes(x = elevation, y = fit, colour = site, group = site),\n      linewidth = 0.75\n    ) +\n    scale_color_manual(values = site_colors, labels = site_labels, name = \"Site\") +\n    scale_fill_manual(values = site_colors, guide = \"none\") +\n    scale_y_continuous(\"Relative abundance (proportion)\", limits = y_limits) +\n    scale_x_continuous(x_label, limits = x_limits) +\n    labs(tag = label_prefix) +\n    base_theme +\n    theme(\n      plot.tag = element_text(size = 12, face = \"bold\", hjust = -0.05)\n    ) +\n    {\n      if (!is.null(effect_label)) {\n        annotate(\n          \"text\",\n          x = Inf, y = Inf,\n          label = effect_label,\n          hjust = 1.02, vjust = 1.2,\n          size = 2.6\n        )\n      }\n    }\n}\n\n# ===== STEP 3: Create Panel A & B (Beta-regression plots) =====\n# Using mod_list and df_list from the Beta-regression model section\nstopifnot(!is.null(mod_list), !is.null(df_list))\nstopifnot(\"helotiales\" %in% names(mod_list), \"sebacinales\" %in% names(mod_list))\nstopifnot(\"helotiales\" %in% names(df_list), \"sebacinales\" %in% names(df_list))\n\n# Shared x-axis limits across Panels A and B\nx_shared <- range(\n  c(df_list[[\"helotiales\"]]$elevation, df_list[[\"sebacinales\"]]$elevation),\n  na.rm = TRUE\n)\n\npanel_A <- plot_betareg_fig4(\n  model = mod_list[[\"helotiales\"]],\n  data = df_list[[\"helotiales\"]],\n  label_prefix = \"A\",\n  y_limits = c(0, 1)\n) +\n  scale_x_continuous(\"\", limits = x_shared) +   # no label — B carries the shared x label\n  annotate(\n    \"text\",\n    x = Inf, y = Inf,\n    label = \"+10.1% per 100 m, p = 0.016\",\n    hjust = 1.02, vjust = 1.2,\n    size = 2.6\n  ) +\n  theme(legend.position = \"none\")               # legend shown only on B\n\npanel_B <- plot_betareg_fig4(\n  model = mod_list[[\"sebacinales\"]],\n  data = df_list[[\"sebacinales\"]],\n  label_prefix = \"B\",\n  y_limits = c(0, 0.75)\n) +\n  scale_x_continuous(\"Elevation (m)\", limits = x_shared) +  # explicit shared x label for A+B column\n  annotate(\n    \"text\",\n    x = Inf, y = Inf,\n    label = \"-10% per 100 m, p = 0.033\",\n    hjust = 1.02, vjust = 1.2,\n    size = 2.6\n  ) +\n  theme(\n    legend.position    = \"bottom\",\n    legend.direction   = \"horizontal\",\n    legend.box         = \"horizontal\",\n    legend.justification = \"center\",\n    legend.title       = element_text(size = 8, face = \"bold\"),\n    legend.text        = element_text(size = 8),\n    legend.key.size    = unit(0.7, \"lines\"),\n    # Pull x-axis title up toward the tick labels (reduce gap between ticks and \"Elevation (m)\")\n    axis.title.x       = element_text(size = 9, margin = margin(t = 1, b = 0)),\n    # Pull legend up toward the x-axis title (reduce gap between label and legend box)\n    legend.box.margin  = margin(t = -6, b = 0, l = 0, r = 0),\n    # Trim panel B's own bottom margin so patchwork's reserved gutter space doesn't float them\n    plot.margin        = margin(t = 2, r = 5, b = 1, l = 5)\n  ) +\n  guides(\n    color = guide_legend(nrow = 1, byrow = TRUE),\n    fill = \"none\"\n  )\n\n# ===== STEP 4: Create Panel C (GLLVM heatmap from p_heat object) =====\n# Load the GLLVM heatmap plot object generated in the GLLVM analysis section\n# ASSUMED OBJECT:\n#   - p_heat: ggplot object created in gllvm_analysis.R (heatmap of genus-level responses)\n#   Stored in: objects/p_heat_gllvm.rds \n\n# Check if p_heat is in workspace; if not, try loading from RDS\nif (!exists(\"p_heat\")) {\n  p_heat_path <- file.path(out_obj_dir, \"p_heat_gllvm.rds\")\n  if (file.exists(p_heat_path)) {\n    p_heat <- readRDS(p_heat_path)\n    message(\"Loaded p_heat from \", p_heat_path)\n  } else {\n    stop(\"p_heat object not found in workspace and p_heat_gllvm.rds not found in \", out_obj_dir)\n  }\n}\n\n# Validate p_heat and fail loudly if it is not a usable ggplot\nif (!inherits(p_heat, \"ggplot\")) {\n  stop(\"p_heat exists but is not a ggplot object. Current class: \", paste(class(p_heat), collapse = \", \"))\n}\n\ntile_rows <- 0L\nbuilt_heat <- ggplot_build(p_heat)\nif (length(built_heat$data) > 0) {\n  tile_rows <- sum(vapply(built_heat$data, nrow, integer(1)))\n}\nif (tile_rows == 0L) {\n  stop(\"p_heat is a ggplot but has no drawable data. Rebuild p_heat in the GLLVM workflow before Figure 4.\")\n}\n\n# Color genus names by order: Helotiales (default),\n# with explicit exceptions for Serendipita (Sebacinales) and Capronia (Chaetothyriales).\ngenus_levels <- levels(p_heat$data$Genus)\nif (is.null(genus_levels)) {\n  genus_levels <- unique(as.character(p_heat$data$Genus))\n}\n\ngenus_order_map <- c(Serendipita = \"Sebacinales\", Capronia= \"Chaetothyriales\") # everything else is Helotiales \norder_colors <- c(\n  Helotiales      = \"#7B4F9E\",  \n  Sebacinales     = \"#E69F00\",  \n  Chaetothyriales  = \"#FF0000\")\n\n# Get genus order from the heatmap data\ngenus_levels <- levels(p_heat$data$Genus)\nif (is.null(genus_levels)) {\n  genus_levels <- unique(as.character(p_heat$data$Genus))\n}\n\n# Assign order to each genus\ngenus_orders <- ifelse(\n  genus_levels %in% names(genus_order_map),\n  genus_order_map[genus_levels],\n  \"Helotiales\"\n)\n\n# Map to colors in the same order as genus_levels\ny_axis_colors <- order_colors[genus_orders]\n\n# Apply directly to the heatmap theme\n# NOTE: scale_x_discrete wraps x-axis labels onto two horizontal lines.\n# Horizontal two-line labels have a much smaller vertical footprint than long\n# diagonal ones, shrinking panel C's bottom gutter so patchwork stops inserting\n# a matching gap below panel B (where \"Elevation (m)\" + legend live).\npanel_C <- p_heat +\n  labs(tag = \"C\") +\n  scale_x_discrete(labels = c(\n    \"Páramo vs forest\"    = \"Páramo\\nvs forest\",\n    \"Subpáramo vs forest\" = \"Subpáramo\\nvs forest\"\n  )) +\n  theme(\n    axis.text.y = element_text(\n      color = y_axis_colors,\n      size  = 8.5,\n      face  = \"italic\",\n      hjust = 1\n    ),\n    axis.text.x       = element_text(size = 8.5, angle = 0, hjust = 0.5, vjust = 1),\n    plot.margin       = margin(t = 5, r = 5, b = 2, l = 5),\n    plot.tag          = element_text(size = 13, face = \"bold\"),\n    legend.title      = element_text(size = 8.5),\n    legend.text       = element_text(size = 7),\n    legend.key.height = unit(0.5, \"cm\"),\n    legend.key.width  = unit(0.4, \"cm\")\n  )\n\n# ===== STEP 5: Combine all three panels with patchwork =====\n# Layout: Beta-regression panels (A & B) on left as 2-row layout, GLLVM (C) on right\nfig4 <- ((panel_A / panel_B) | panel_C) +\n  plot_layout(\n    widths = c(1.5, 0.75)   # Give panel C more room so x-axis labels are less cramped\n    # guides and axis_titles NOT collected: each panel owns its own legend/label.\n    # Panel A: no legend, no x label. Panel B: horizontal legend below, x label in place.\n    # Panel C: its own heatmap legend, unaffected.\n  )\n\n# ===== STEP 6: Save the combined figure =====\nggsave(\n  filename = file.path(out_fig_dir, \"Figure_4_betareg_GLLVM_combined.png\"),\n  plot = fig4,\n  width = 22, height = 14, units = \"cm\", dpi = 900, bg = \"white\",\n  device = if (requireNamespace(\"ragg\", quietly = TRUE)) ragg::agg_png else \"png\"\n)\n```\n:::\n\n\n### 6.3 GLLVM: OTU-level habitat responses\n\nWe modelled OTU counts using a generalized linear latent variable model (GLLVM; negative binomial distribution, log link), with habitat (forest, subpáramo, páramo) as a fixed effect, log library size as an offset, and random intercepts for site and individual plants (Unique_ID). One latent variable was included to account for residual correlation among taxa. The final model (log-likelihood = −37,616; AIC = 80,295) provided the best balance between fit and parsimony. It substantially outperformed earlier versions with nested random effects (AIC = 186,832), and attempts to increase the number of latent variables to two worsened performance (ΔAIC ≈ 12,700) and produced a singular information matrix, indicating over-parameterization. Simplifying the random-effects structure and filtering rare taxa also improved convergence and reduced overdispersion while retaining ecological signal.\n\nModel fit was evaluated using Dunn–Smyth residual diagnostics (Fig. S8). Habitat coefficients (β) were extracted for each OTU from the fixed-effects matrix. To obtain genus-level responses, OTUs were restricted to those assigned to a genus (excluding incertae sedis) and weighted by their total read abundance across samples. For each genus, we computed the abundance-weighted mean β for páramo and subpáramo relative to forest. Uncertainty was summarized using a weighted bootstrap (R = 500) resampling OTUs within genera with probabilities proportional to total abundance; 2.5–97.5% quantiles were used as 95% confidence intervals. These summaries were used to generate the heatmap and barplot shown in Figure 4. The full OTU-level coefficient table is provided in Data_S2_GLLVM_table.csv.\n\n![](figures/Fig_S8_GLLVM_diagnostics.png)\n\n**Figure S8**: Diagnostic plots for the negative-binomial GLLVM (Dunn–Smyth residuals). *Code: see \"GLLVM model fitting + coefficient summaries\" below.*\n\nFor transparency, we provide a short preview of the genus-level GLLVM summaries below. The complete OTU- and genus-level coefficient table is available as Data S2 (Data_S2_GLLVM_table.csv).\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Data S2 (preview). Selected columns from the GLLVM genus-level summary. The full table with all metrics is provided as a CSV file.\n\n|Order          |Genus        | n_OTUs| w_mean_beta_paramo| w_mean_beta_subparamo| perc_enriched_paramo_w| perc_enriched_subparamo_w|\n|:--------------|:------------|------:|------------------:|---------------------:|----------------------:|-------------------------:|\n|Coniochaetales |Coniochaeta  |      2|            254.379|               -25.536|          2.048010e+115|             -1.000000e+02|\n|Helotiales     |Acephala     |      1|             78.144|                69.862|           8.663205e+35|              2.190394e+32|\n|Helotiales     |Hyaloscypha  |      3|             26.861|                29.053|           3.743955e+14|              6.764441e+13|\n|Helotiales     |Pezicula     |      5|             26.640|                29.280|           1.824961e+09|             -9.894700e+01|\n|Helotiales     |Lachnum      |      3|             -1.529|                 9.013|           1.016873e+08|              2.107609e+04|\n|Sclerococcales |Sclerococcum |      4|             24.669|                -8.648|           2.210442e+06|             -9.989400e+01|\n|Mortierellales |Mortierella  |      5|             -7.650|               -34.063|           1.011728e+04|             -1.000000e+02|\n|Helotiales     |Gyoerffyella |      3|              2.739|                 0.188|           1.021700e+01|             -9.967900e+01|\n|Ostropales     |Cryptodiscus |      3|            -15.238|                12.611|          -1.947200e+01|              6.019926e+04|\n|Helotiales     |Pezoloma     |      2|             -6.125|                -4.096|          -9.964100e+01|             -9.684900e+01|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"GLLVM model fitting + coefficient summaries (executed on server)\"}\n# GLLVM analysis was executed on the server.\n# The complete workflow (data filtering, model fitting, diagnostics, and genus-level summaries) is provided in the repository:\n#   scripts/gllvm_analysis.R\n#\n# Key outputs saved:\n#   - figures/Fig_S8_GLLVM_diagnostics.png\n#   - tables/File_S2_GLLVM_table.csv\n#   - objects/fit_nb_2.rds  # fitted model object - too large to include in repo\n```\n:::\n\n\n## Section 7: Functional guilds\n\nFunctional guilds from root samples were assigned using FUNGuild based on the curated taxonomic strings exported from the phyloseq object. OTUs with a valid confidence ranking in the FUNGuild output were retained for downstream summaries. Guild labels were additionally collapsed into a primary-guild hierarchy (Ericoid mycorrhizal \\> other mycorrhizal \\> endophyte \\> pathotroph \\> saprotroph \\> other) to simplify interpretation. Figure S7 summarizes mean guild-associated read abundance per sample across habitats.\n\n![](figures/Fig_S7_FunGuild.png)\n\n**Figure S7**: Mean relative read abundance per sample of fungal functional guilds across forest, subpáramo, and páramo habitats, based on FUNGuild annotations. Only root samples. *Code: see \"FUNGuild functional annotation\" below.*\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"FUNGuild functional annotation (external script)\"}\n# Functional guild assignment was performed using FUNGuild prior to figure generation.\n#\n# The full annotation workflow is available in the GitHub repository:\n#   scripts/funguild_script.R\n#\n# Input:\n#  - Taxonomically annotated ASV/OTU table\n#\n# Output:\n#  - Table of guild assignments per taxon\n#  - Mean read abundances per sample and habitat\n#\n# Figure S7 was generated from these outputs and is included above as a PNG.\n```\n:::\n\n\n## Section 8: Phylogenetic community structure\n\nPhylogenetic community structure was quantified using Net Relatedness Index (NRI; based on MPD) and Nearest Taxon Index (NTI; based on MNTD), calculated under a taxa-label null model with 999 randomizations using both abundance-weighted (aw) and presence–absence (pa) versions. Habitat-level summaries are reported as median (IQR) (Table S20). Habitat and site effects on abundance-weighted metrics were evaluated with linear models (habitat + site; Table S21). Model diagnostics for the NTI_aw model are available in Fig. S9.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S20. Median (IQR) of NRI and NTI across habitats, calculated using abundance-weighted (aw) and presence–absence (pa) metrics. Positive values indicate phylogenetic clustering relative to null expectations.\n\n|Habitat   |  n|NRI_aw       |NTI_aw       |NRI_pa       |NTI_pa       |\n|:---------|--:|:------------|:------------|:------------|:------------|\n|forest    | 25|0.991 (3.02) |3.053 (1.70) |0.711 (2.19) |5.764 (2.13) |\n|paramo    | 15|1.435 (1.85) |3.277 (1.62) |0.831 (2.81) |4.930 (2.06) |\n|subparamo | 20|1.675 (1.77) |2.831 (1.40) |0.395 (1.50) |4.876 (2.49) |\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table S21. ANOVA summaries for linear models of abundance-weighted NTI and NRI (habitat + site).\n\n|Response |Predictor | df|      F|      p|\n|:--------|:---------|--:|------:|------:|\n|NTI_aw   |habitat   |  2| 0.5106| 0.6030|\n|NTI_aw   |site      |  3| 1.8164| 0.1551|\n|NTI_aw   |Residuals | 54|     NA|     NA|\n|NRI_aw   |habitat   |  2| 1.2729| 0.2883|\n|NRI_aw   |site      |  3| 3.4206| 0.0235|\n|NRI_aw   |Residuals | 54|     NA|     NA|\n\n\n:::\n:::\n\n\n![](figures/Fig_S9_NTI_aw_diagnostics.png)\n\n**Figure S9**: Diagnostic plots for the NTI_aw linear model.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"NTI/NRI computation + summaries (executed on remote server)\"}\n# Key outputs saved:\n#   - figures/Fig_S9_NTI_aw_diagnostics.png\n#   - tables/Table_S20_NRI_NTI_median_IQR.csv\n#   - tables/Table_S21_NRI_NTI_ANOVA.csv\n\nlibrary(phyloseq)\nlibrary(picante)\nlibrary(ape)\nlibrary(phangorn)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(patchwork)\n\nset.seed(1)\n\nps <- tree_ps #phyloseq object with tree\n\nstopifnot(exists(\"ps\"))\ntr2 <- phy_tree(ps)\nstopifnot(!is.null(tr2))\n\n# Root tree if needed\nif (!ape::is.rooted(tr2)) tr2 <- phangorn::midpoint(tr2)\n\n## 1) samples x taxa abundance matrix\ncomm <- as(otu_table(ps), \"matrix\")\nif (taxa_are_rows(ps)) comm <- t(comm)\n\n## 2) align taxa with tree tips\nkeep_taxa <- intersect(colnames(comm), tr2$tip.label)\ncomm <- comm[, keep_taxa, drop = FALSE]\ntr2  <- ape::keep.tip(tr2, keep_taxa)\n\n## 3) optional: drop ultra-rare taxa \nmin_total_taxon_reads <- 10\nkeep_taxa2 <- colSums(comm) >= min_total_taxon_reads\ncomm <- comm[, keep_taxa2, drop = FALSE]\ntr2  <- ape::keep.tip(tr2, colnames(comm))\n\n## 4) metadata aligned to comm\nmd <- as(sample_data(ps), \"data.frame\")\nmd <- md[rownames(comm), , drop = FALSE]\nmd$habitat <- droplevels(factor(md$habitat))\nmd$site    <- droplevels(factor(md$site))\n\n## 5) phylogenetic distances among taxa\ndist_phy <- cophenetic(tr2)\n\n## 6) null model tests\nmpd_aw  <- ses.mpd (comm, dist_phy, null.model = \"taxa.labels\",\n                    runs = 999, abundance.weighted = TRUE)\nmntd_aw <- ses.mntd(comm, dist_phy, null.model = \"taxa.labels\",\n                    runs = 999, abundance.weighted = TRUE)\n\ncomm_pa <- 1 * (comm > 0)\nmpd_pa  <- ses.mpd (comm_pa, dist_phy, null.model = \"taxa.labels\",\n                    runs = 999, abundance.weighted = FALSE)\nmntd_pa <- ses.mntd(comm_pa, dist_phy, null.model = \"taxa.labels\",\n                    runs = 999, abundance.weighted = FALSE)\n\n## 7) per-sample output table\nout <- data.frame(\n  sample = rownames(comm),\n  NRI_aw = -mpd_aw$mpd.obs.z,\n  NTI_aw = -mntd_aw$mntd.obs.z,\n  NRI_pa = -mpd_pa$mpd.obs.z,\n  NTI_pa = -mntd_pa$mntd.obs.z,\n  stringsAsFactors = FALSE\n)\nrownames(out) <- out$sample\n\n# Drop any sample with NA (e.g., too few taxa after filtering)\nout <- out[complete.cases(out[, c(\"NRI_aw\",\"NTI_aw\",\"NRI_pa\",\"NTI_pa\")]), ]\nout <- cbind(out, md[rownames(out), c(\"habitat\",\"site\"), drop = FALSE])\nout$habitat <- droplevels(factor(out$habitat))\nout$site    <- droplevels(factor(out$site))\n\n## 8) Table S20: median (IQR) per habitat, formatted as \"median (IQR)\"\nfmt_med_iqr <- function(x) sprintf(\"%.3f (%.2f)\", median(x, na.rm=TRUE), IQR(x, na.rm=TRUE))\n\ntab_s20 <- out %>%\n  group_by(habitat) %>%\n  summarise(\n    n = n(),\n    NRI_aw = fmt_med_iqr(NRI_aw),\n    NTI_aw = fmt_med_iqr(NTI_aw),\n    NRI_pa = fmt_med_iqr(NRI_pa),\n    NTI_pa = fmt_med_iqr(NTI_pa),\n    .groups = \"drop\"\n  ) %>%\n  rename(Habitat = habitat)\n\nwrite.csv(tab_s20, file.path(out_tab_dir, \"Table_S20_NRI_NTI_median_IQR.csv\"), row.names = FALSE)\n\n## 9) Table S21: ANOVA summaries (NTI_aw and NRI_aw models)\nm_NTI_aw <- lm(NTI_aw ~ habitat + site, data = out)\nm_NRI_aw <- lm(NRI_aw ~ habitat + site, data = out)\n\na_NTI <- as.data.frame(anova(m_NTI_aw))\na_NRI <- as.data.frame(anova(m_NRI_aw))\n\ntab_s21 <- bind_rows(\n  data.frame(Response = \"NTI_aw\", Predictor = rownames(a_NTI), df = a_NTI$Df, F = a_NTI$`F value`, p = a_NTI$`Pr(>F)`),\n  data.frame(Response = \"NRI_aw\", Predictor = rownames(a_NRI), df = a_NRI$Df, F = a_NRI$`F value`, p = a_NRI$`Pr(>F)`)\n) %>%\n  filter(Predictor %in% c(\"habitat\",\"site\",\"Residuals\"))\n\nwrite.csv(tab_s21, file.path(out_tab_dir, \"Table_S21_NRI_NTI_ANOVA.csv\"), row.names = FALSE)\n\n## 10) Figure S9: diagnostics for NTI_aw model\ndiagdf <- data.frame(\n  fitted = fitted(m_NTI_aw),\n  resid  = resid(m_NTI_aw),\n  stdres = rstandard(m_NTI_aw),\n  cooks  = cooks.distance(m_NTI_aw),\n  hat    = hatvalues(m_NTI_aw)\n)\n\np1 <- ggplot(diagdf, aes(fitted, resid)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  geom_point(alpha = 0.7, size = 1.8) +\n  geom_smooth(method = \"loess\", se = FALSE, linewidth = 0.5) +\n  labs(x = \"Fitted values\", y = \"Residuals\", title = \"Residuals vs fitted\") +\n  theme_bw(base_size = 10)\n\np2 <- ggplot(diagdf, aes(sample = stdres)) +\n  stat_qq(alpha = 0.7, size = 1.5) +\n  stat_qq_line() +\n  labs(title = \"Normal Q–Q (standardized residuals)\") +\n  theme_bw(base_size = 10)\n\np3 <- ggplot(diagdf, aes(seq_along(cooks), cooks)) +\n  geom_point(alpha = 0.7, size = 1.8) +\n  geom_hline(yintercept = 0.5, linetype = \"dashed\") +\n  labs(x = \"Observation index\", y = \"Cook's distance\", title = \"Influence (Cook's distance)\") +\n  theme_bw(base_size = 10)\n\np4 <- ggplot(diagdf, aes(seq_along(hat), hat)) +\n  geom_point(alpha = 0.7, size = 1.8) +\n  labs(x = \"Observation index\", y = \"Leverage (hat)\", title = \"Leverage\") +\n  theme_bw(base_size = 10)\n\npanel <- (p1 | p2) / (p3 | p4) + plot_annotation(title = \"NTI_aw model diagnostics\")\n\nggsave(\n  filename = file.path(out_fig_dir, \"Fig_S9_NTI_aw_diagnostics.png\"),\n  plot = panel,\n  width = 10, height = 7, dpi = 900, bg = \"white\"\n)\n```\n:::\n\n\n## Section 9: Soil physicochemical context\n\nTo provide environmental context for the elevational gradients sampled in this study, we quantified bulk soil physicochemical properties from one composite topsoil sample (0–15 cm) collected at each sampling location (n = 12; one per location). Because soil chemistry was measured once per location, these data are interpreted descriptively and were not used for formal statistical inference among habitats or sites.\n\nThe full soil dataset, including all measured variables, is provided as Table S15 and is archived in the repository as \"Data_S3_soil.csv\".\n\n![](figures/Fig_S10_soil.png)\\\n\\\n**Figure S10**: Correlation heatmap of bulk soil physicochemical variables measured at each sampling location (n = 12). Colors indicate Pearson correlation among soil variables and elevation.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}